function G = func_G(L3,L4,L5,g,m2,m3,m4,m5,m6,q2,q3,q4,q5)
%FUNC_G
%    G = FUNC_G(L3,L4,L5,G,M2,M3,M4,M5,M6,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Feb-2026 13:38:33

t2 = sin(q2);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q3);
t6 = cos(q5);
t7 = cos(q4);
t8 = sin(q5);
t9 = q2+q3;
t10 = cos(t9);
t11 = sin(t9);
G = [0.0;g.*(L3.*m2.*t2.*4.0+L3.*m3.*t2.*8.0+L3.*m4.*t2.*8.0+L3.*m5.*t2.*8.0+L3.*m6.*t2.*8.0-L4.*m3.*t2.*t5+L4.*m3.*t3.*t4-L4.*m4.*t2.*t5.*8.0+L4.*m4.*t3.*t4.*8.0-L4.*m5.*t2.*t5.*8.0+L4.*m5.*t3.*t4.*8.0+L5.*m4.*t2.*t5.*8.0-L5.*m4.*t3.*t4.*8.0-L4.*m6.*t2.*t5.*8.0+L4.*m6.*t3.*t4.*8.0-L5.*m6.*t2.*t5.*t6.*8.0+L5.*m6.*t3.*t4.*t6.*8.0-L5.*m6.*t2.*t4.*t7.*t8.*8.0-L5.*m6.*t3.*t5.*t7.*t8.*8.0).*(-1.0./8.0);-g.*m6.*(L4.*t10+L5.*t6.*t10-L5.*t7.*t8.*t11)-L4.*g.*m3.*t10.*(1.0./8.0)-L4.*g.*m5.*t10-g.*m4.*t10.*(L4-L5);L5.*g.*m6.*t8.*t10.*sin(q4);L5.*g.*m6.*(t8.*t11-t6.*t7.*t10);0.0];
