Description of load_robot
Home > arte3.1.4 > lib > load_robot.m
load_robot
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function robot = load_robot(varargin)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   LOAD_ROBOT Loads a data structure corresponding to the specified robot.
     robot = LOAD_ROBOT(MANUFACTURER, VERSION) returns a robot data
     structure of the specified robot.  Each robot parameters' are stored in
     the directory named robots/manufacturer/version. For example:
   Example:
   robot =  load_robot('ABB', 'IRB140')
   gets the available data for the ABB IRB140 robotic arm whose
   parameters are stored in the directory robots/ABB/IRB140
   robot = LOAD_ROBOT(PATH) specifies a relative path to the robots
   directory. For example:
   robot =  load_robot('ABB/IRB140')
   robot = LOAD_ROBOT() with no arguments opens a dialog box to select a
   robot's parameters file.
   Execute
   SUPPORTED_ROBOTS to see a list of all supported robots.
   The robot data structure consists of the following fields:
    See also SUPPORTED_ROBOTS.
   Author: Arturo Gil. Universidad Miguel Hernï¿½ndez de Elche. email:
   arturo.gil@umh.es date:   02/01/2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
drawrobot3d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
program_robot Para la simulación de un programa
demos Copyright (C) 2012, by Arturo Gil Aparicio
direct_jacobian_demo DIRECT JACOBIAN DEMO
follow_line_pa10 Copyright (C) 2012, by Arturo Gil Aparicio
forwarddynamics_demo SCRIPT TEST THE DIRECT DYNAMICS OF THE PUMA 560 ROBOT
forwarddynamics_demo_3dof SCRIPT TEST THE DIRECT DYNAMICS OF THE PUMA 560 ROBOT
inversedynamics_2DOFplanar SCRIPT TEST FOR THE 2DOF arm
inversedynamics_3DOFplanar SCRIPT TEST FOR THE 3 DOF planar manipulator
inversedynamics_puma560 SCRIPT TO TEST THE DYNAMICS OF THE PUMA 560 ROBOT
manufacturing_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
draw_errors_scara PROPAGATE A GAUSSIAN ERROR DISTRIBUTION OF EACH JOINT TO AN ERROR IN
draw_errors_scara_monte_carlo THE DEMO PRESENTS AN ERROR PROPAGATION USING A MONTE-CARLO METHOD
follow_line_scara FOLLOW A LINE IN SPACE WITH A SCARA ROBOT
motor_selection SCRIPT TO FIND THE TORQUES AT EACH JOINT FOR DIFFERENT MOTION STATES OF
plot_every_robot_demo SCRIPT TEST TO LOAD ALL ROBOTS
spot_welding_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
transform_to_own %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   LOAD_ROBOT Loads a data structure corresponding to the specified robot.
%
%
%     robot = LOAD_ROBOT(MANUFACTURER, VERSION) returns a robot data
%     structure of the specified robot.  Each robot parameters' are stored in
%     the directory named robots/manufacturer/version. For example:
%
%   Example:
%   robot =  load_robot('ABB', 'IRB140')
%
%   gets the available data for the ABB IRB140 robotic arm whose
%   parameters are stored in the directory robots/ABB/IRB140
%
%   robot = LOAD_ROBOT(PATH) specifies a relative path to the robots
%   directory. For example:
%   robot =  load_robot('ABB/IRB140')
%
%   robot = LOAD_ROBOT() with no arguments opens a dialog box to select a
%   robot's parameters file.
%
%
%   Execute
%   SUPPORTED_ROBOTS to see a list of all supported robots.
%
%   The robot data structure consists of the following fields:
%
%    See also SUPPORTED_ROBOTS.
%
%   Author: Arturo Gil. Universidad Miguel Hernï¿½ndez de Elche. email:
%   arturo.gil@umh.es date:   02/01/2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
%function robot = load_robot(manufacturer, version)
function robot = load_robot(varargin)
global configuration
%process variable number of arguments
%if the function is called with no arguments then a dialog
%box is used to retrieve the absolute path of the parameters.m file.
if nargin==0
   [FileName,PathName,FilterIndex] = uigetfile({'*.m','Parameter-files (*.m)'},'Pick a robot parameters.m file', 'MultiSelect', 'off');
   full_name=[PathName '/' FileName];
   cd(PathName);
elseif nargin==1 % the relative path is expressed in a single argument%load base libpath
    cd(configuration.libpath);
    % go to the directory where the robot is stored
    temp_path = [ configuration.libpath '/robots/' varargin{1}];
    cd(temp_path);
    %make a command to evaluate the parameter.m file at this directory
    full_name = [temp_path '/parameters.m'];
elseif nargin==2 % the relative path is expressed in the 'manufacturer', 'version' style
    manufacturer = varargin{1};
    version = varargin{2};
    %load base libpath
    cd(configuration.libpath);
    % go to the directory where the robot is stored
    temp_path = [ configuration.libpath '/robots/' manufacturer '/' version];
    cd(temp_path);
    %make a command to evaluate the parameter.m file at this directory
    full_name = [temp_path '/parameters.m'];
end
%initialize robot data structure
robot=[];
%Eval parameters file for the selected robot
%eval(command);
%check whether the parameters.m file exists at the required location
if exist(full_name,'file')==2
    robot=eval('parameters');
    %now draw robot
    drawrobot3d(robot,zeros(1,robot.DOF));
    %default view
    axis(robot.axis);
else %if there's no parameters.m file
    fprintf('ERROR: No valid parameters.m file found. Please check the following directory')
    full_name
end