Description of kinematics_demo
Home > arte3.1.4 > demos > kinematics_demo.m
kinematics_demo
PURPOSE
SCRIPT TEST FOR THE KINEMATIC PROBLEM
SYNOPSIS
This is a script file.
DESCRIPTION
 SCRIPT TEST FOR THE KINEMATIC PROBLEM
CROSS-REFERENCE INFORMATION
This function calls:
directkinematic DIRECTKINEMATIC Direct Kinematic for serial robots.
inversekinematic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
test_joints Test whether any of the joint angles exceeds the mechanical
adjust_view ADJUST_VIEW(ROBOT)
drawrobot3d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
demos Copyright (C) 2012, by Arturo Gil Aparicio
SOURCE CODE
% SCRIPT TEST FOR THE KINEMATIC PROBLEM
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
close all
fprintf('\nTHE DEMO PRESENTS THE DIRECT AND INVERSE KINEMATIC PROBLEM')
%there are eight possible solutions for the
%inverse kinematic problem for these robots
%
%Try differen configurations
q = [0.1 -0.3 0.3 0.4 0.5 0.6]
%q = [pi/4 pi/4 pi/8 pi/8 pi/8 pi/8]
%q = [-0.9*pi 0 0 0 pi/3 0];
%q = [pi/4 pi/4 pi/4 0 0 0];
%load robot parameters
% you can try different robots
%robot=load_robot('abb', 'IRB140'); n_solutions = 8;
%robot=load_robot('abb', 'IRB1600_6_120'); n_solutions = 8;
%robot=load_robot('abb', 'IRB1600_X145_M2004'); n_solutions = 8;
%robot=load_robot('abb', 'IRB1600ID'); n_solutions = 8;
%robot=load_robot('abb', 'IRB2400'); n_solutions = 8;
%robot=load_robot('abb', 'IRB4400'); n_solutions = 8;
%robot=load_robot('abb', 'IRB4600'); n_solutions = 8;
%robot=load_robot('abb', 'IRB52'); n_solutions = 8;
%robot=load_robot('abb', 'IRB6620'); n_solutions = 8;
%robot=load_robot('abb', 'IRB6620LX'); n_solutions = 4;
%robot=load_robot('abb', 'IRB6650S_125_350'); n_solutions = 8;
%robot=load_robot('abb', 'IRB7600_150'); n_solutions = 8;
%robot=load_robot('abb', 'IRB7600_400_255_m2000'); n_solutions = 8;
%robot=load_robot('abb', 'IRB7600_500_230'); n_solutions = 8;
%ADEPT
%robot=load_robot('adept', 'Viper_s1700D'); n_solutions = 8;
%EPSON
%robot=load_robot('epson', 'Prosix_C3_A601C'); n_solutions = 8;
%FANUC
%robot=load_robot('fanuc', 'LR_MATE_200iC'); n_solutions = 8;
%KUKA
%robot=load_robot('kuka', 'KR30_jet'); n_solutions = 8;
%robot=load_robot('kuka', 'KR5_2ARC_HW'); n_solutions = 8;
%robot=load_robot('kuka', 'KR5_arc'); n_solutions = 8;
%robot=load_robot('kuka', 'KR5_sixx_R650'); n_solutions = 8;
%robot=load_robot('kuka', 'KR5_sixx_R850'); n_solutions = 8;
%robot=load_robot('kuka', 'KR6_2'); n_solutions = 8;
%robot=load_robot('kuka', 'KR90_R2700_pro'); n_solutions = 8;
%robot=load_robot('kuka', 'KR90_R3100_EXTRA'); n_solutions = 8;
%robot=load_robot('kuka', 'KR_1000_1300_TITAN'); n_solutions = 8;
%robot=load_robot('kuka', 'KR_16_arc_HW'); n_solutions = 8;
%robot=load_robot('kuka', 'KR_30_L16_2'); n_solutions = 8;
%MITSUBISHI
%robot=load_robot('mitsubishi', 'pa-10'); n_solutions = 8;%q=[0 0 0 0 0 0];
%robot=load_robot('mitsubishi', 'rv-6s'); n_solutions = 8;%q=[0 0 0 0 0 0];
%STANFORD ARM
%robot=load_robot('stanford', ''); n_solutions = 4;%q=[0 0 0 0 0 0];
%STAUBLI
%robot=load_robot('staubli', 'RX160L'); n_solutions = 8; q=[0.1 -0.6 1 0.4 0.5 0.6]
%UNIMATE
%robot=load_robot('unimate', 'puma560'); n_solutions = 8;
%adjust 3D view as desired
adjust_view(robot)
%there are just 2 solutions for these robots
%q = [pi/2 0.2 0.8 pi/4]
%q = [-pi/4 pi/2 0.5 pi]
%robot=load_robot('kuka', 'KR5_scara_R350_Z200'); n_solutions = 2;
%robot=load_robot('example', 'scara'); n_solutions = 2;
%robot=load_robot('example', '2dofplanar'); n_solutions = 2;
%robot=load_robot('example', '3dofplanar'); n_solutions = 2;
%robot=load_robot('example', 'prismatic');n_solutions = 1; %just one possible solutions for this case
%draw the robot
drawrobot3d(robot, q)
%Now compute direct kinematics for this position q
T = directkinematic(robot, q)
%Set to zero if you want to see the robot transparent
robot.graphical.draw_transparent=1;
%Set to one if you want to see the DH axes
%abb.graphical.draw_axes=1;
%Call the inversekinematic for this robot
% all the possible solutions are stored at qinv
% at least, one of the possible solutions should be coincident with q
qinv = inversekinematic(robot, T);
fprintf('\nNOW WE CAN REPRESENT THE DIFFERENT SOLUTIONS TO ACHIEVE THE SAME POSITION AND ORIENTATION\n')
fprintf('\nNot that some solutions may not be feasible. Some joints may be out of range\n')
%check that all of them are possible solutions!
for i=1:size(qinv,2),
    Ti = directkinematic(robot, qinv(:,i)) %Ti is constant for the different solutions
    % Note that all the solutions may not be feasible. Some of the joints may
    % be out of range. You can test this situation with test_joints
    test_joints(robot, qinv(:,i));
    %now draw the robot to see the solution
    drawrobot3d(robot, qinv(:,i))
    pause(2);
end