Description of teach
Home > arte3.1.4 > RAPID > teach.m
teach
PURPOSE
SYNOPSIS
function varargout = teach(varargin)
DESCRIPTION
 TEACH MATLAB code for teach.fig
      TEACH, by itself, creates a new TEACH or raises the existing
      singleton*.
      H = TEACH returns the handle to a new TEACH or the handle to
      the existing singleton*.
      TEACH('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in TEACH.M with the given input arguments.
      TEACH('Property','Value',...) creates a new TEACH or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before teach_OpeningFcn gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to teach_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
compute_configuration %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
select_closest_joint_coordinates %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
select_configuration %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
test_joint_limits %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T2quaternion %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
directkinematic DIRECTKINEMATIC Direct Kinematic for serial robots.
inversekinematic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
quaternion2T %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
test_joints Test whether any of the joint angles exceeds the mechanical
drawrobot3d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
vect_arrow %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
demos Copyright (C) 2012, by Arturo Gil Aparicio
manufacturing_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
spot_welding_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
SUBFUNCTIONS
function teach_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = teach_OutputFcn(hObject, eventdata, handles)
function popupmenu_instruction_Callback(hObject, eventdata, handles)
function popupmenu_instruction_CreateFcn(hObject, eventdata, handles)
function listbox1_Callback(hObject, eventdata, handles)
function listbox1_CreateFcn(hObject, eventdata, handles)
function popupmenu_target_point_Callback(hObject, eventdata, handles)
function popupmenu_target_point_CreateFcn(hObject, eventdata, handles)
function popupmenu_through_point_Callback(hObject, eventdata, handles)
function popupmenu_through_point_CreateFcn(hObject, eventdata, handles)
function popupmenu_speed_Callback(hObject, eventdata, handles)
function popupmenu_speed_CreateFcn(hObject, eventdata, handles)
function pushbutton1_Callback(hObject, eventdata, handles)
function popupmenu_precision_Callback(hObject, eventdata, handles)
function popupmenu_precision_CreateFcn(hObject, eventdata, handles)
function slider_q1_Callback(hObject, eventdata, handles)
function slider_q1_CreateFcn(hObject, eventdata, handles)
function slider_q2_Callback(hObject, eventdata, handles)
function slider_q2_CreateFcn(hObject, eventdata, handles)
function slider_q3_Callback(hObject, eventdata, handles)
function slider_q3_CreateFcn(hObject, eventdata, handles)
function slider_q4_Callback(hObject, eventdata, handles)
function slider_q4_CreateFcn(hObject, eventdata, handles)
function slider_q5_Callback(hObject, eventdata, handles)
function slider_q5_CreateFcn(hObject, eventdata, handles)
function slider_q6_Callback(hObject, eventdata, handles)
function slider_q6_CreateFcn(hObject, eventdata, handles)
function pushbutton_x_minus_Callback(hObject, eventdata, handles)
function pushbutton_x_plus_Callback(hObject, eventdata, handles)
function pushbutton_y_plus_Callback(hObject, eventdata, handles)
function pushbutton_y_minus_Callback(hObject, eventdata, handles)
function pushbutton_z_plus_Callback(hObject, eventdata, handles)
function pushbutton_z_minus_Callback(hObject, eventdata, handles)
function edit_q1_Callback(hObject, eventdata, handles)
function edit_q1_CreateFcn(hObject, eventdata, handles)
function edit_q2_Callback(hObject, eventdata, handles)
function edit_q2_CreateFcn(hObject, eventdata, handles)
function edit_q3_Callback(hObject, eventdata, handles)
function edit_q3_CreateFcn(hObject, eventdata, handles)
function edit_q4_Callback(hObject, eventdata, handles)
function edit_q4_CreateFcn(hObject, eventdata, handles)
function edit_q5_Callback(hObject, eventdata, handles)
function edit_q5_CreateFcn(hObject, eventdata, handles)
function edit_q6_Callback(hObject, eventdata, handles)
function edit_q6_CreateFcn(hObject, eventdata, handles)
function pushbutton_load_Callback(hObject, eventdata, handles)
function pushbutton_save_Callback(hObject, eventdata, handles)
function pushbutton_simulate_Callback(hObject, eventdata, handles)
function edit_nx_Callback(hObject, eventdata, handles)
function edit_nx_CreateFcn(hObject, eventdata, handles)
function edit_ox_Callback(hObject, eventdata, handles)
function edit_ox_CreateFcn(hObject, eventdata, handles)
function edit_ax_Callback(hObject, eventdata, handles)
function edit_ax_CreateFcn(hObject, eventdata, handles)
function edit_pxt_Callback(hObject, eventdata, handles)
function edit_pxt_CreateFcn(hObject, eventdata, handles)
function edit_ny_Callback(hObject, eventdata, handles)
function edit_ny_CreateFcn(hObject, eventdata, handles)
function edit_oy_Callback(hObject, eventdata, handles)
function edit_oy_CreateFcn(hObject, eventdata, handles)
function edit_ay_Callback(hObject, eventdata, handles)
function edit_ay_CreateFcn(hObject, eventdata, handles)
function edit_pyt_Callback(hObject, eventdata, handles)
function edit_pyt_CreateFcn(hObject, eventdata, handles)
function edit_nz_Callback(hObject, eventdata, handles)
function edit_nz_CreateFcn(hObject, eventdata, handles)
function edit_oz_Callback(hObject, eventdata, handles)
function edit_oz_CreateFcn(hObject, eventdata, handles)
function edit_az_Callback(hObject, eventdata, handles)
function edit_az_CreateFcn(hObject, eventdata, handles)
function edit_pzt_Callback(hObject, eventdata, handles)
function edit_pzt_CreateFcn(hObject, eventdata, handles)
function pushbutton_moveT_Callback(hObject, eventdata, handles)
function edit_Q0_Callback(hObject, eventdata, handles)
function edit_Q0_CreateFcn(hObject, eventdata, handles)
function edit_Q1_Callback(hObject, eventdata, handles)
function edit_Q1_CreateFcn(hObject, eventdata, handles)
function edit_Q2_Callback(hObject, eventdata, handles)
function edit_Q2_CreateFcn(hObject, eventdata, handles)
function edit_Q3_Callback(hObject, eventdata, handles)
function edit_Q3_CreateFcn(hObject, eventdata, handles)
function edit_pxq_Callback(hObject, eventdata, handles)
function edit_pxq_CreateFcn(hObject, eventdata, handles)
function edit_pyq_Callback(hObject, eventdata, handles)
function edit_pyq_CreateFcn(hObject, eventdata, handles)
function edit_pzq_Callback(hObject, eventdata, handles)
function edit_pzq_CreateFcn(hObject, eventdata, handles)
function pushbutton_moveQ_Callback(hObject, eventdata, handles)
function pushbutton_save_target_point_Callback(hObject, eventdata, handles)
function edit_target_point_Callback(hObject, eventdata, handles)
function edit_target_point_CreateFcn(hObject, eventdata, handles)
function popupmenu6_Callback(hObject, eventdata, handles)
function popupmenu6_CreateFcn(hObject, eventdata, handles)
function pushbutton_simulate_instruction_Callback(hObject, eventdata, handles)
function pushbutton_save_instruction_Callback(hObject, eventdata, handles)
function slider_q1_KeyPressFcn(hObject, eventdata, handles)
function popupmenu_base_end_Callback(hObject, eventdata, handles)
function popupmenu_base_end_CreateFcn(hObject, eventdata, handles)
function update_T_Q()
function [T,Q,P]=get_TQ_from_dialog()
function update_sliders()
function path=lineal_path_plan(q_ini, q_final)
function path=lineal_path_planXYZ(P_ini, P_final)
function follow_line(P_ini,P_final)
function draw_target_points()
function tp = construct_target(target_num)
function [name, Q, T, conf]=get_targetpoint_from_string(a)
function [instruction_matlab, instruction_rapid, tp1, tp2, joint_coord]=build_instruction_to_eval()
function [instruction_matlab, instruction_rapid]=build_instruction_to_save()
function popupmenu_line_reorient_Callback(hObject, eventdata, handles)
function popupmenu_line_reorient_CreateFcn(hObject, eventdata, handles)
function pushbutton_show_target_point_Callback(hObject, eventdata, handles)
function pushbutton_show_target_point_KeyPressFcn(hObject, eventdata, handles)
function popupmenu_resolution_Callback(hObject, eventdata, handles)
function popupmenu_resolution_CreateFcn(hObject, eventdata, handles)
function pushbutton_reset_all_Callback(hObject, eventdata, handles)
function pushbutton_save_target_point_KeyPressFcn(hObject, eventdata, handles)
function index=find_closest(q,qi)
SOURCE CODE
function varargout = teach(varargin)
%
% TEACH MATLAB code for teach.fig
%      TEACH, by itself, creates a new TEACH or raises the existing
%      singleton*.
%
%      H = TEACH returns the handle to a new TEACH or the handle to
%      the existing singleton*.
%
%      TEACH('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in TEACH.M with the given input arguments.
%
%      TEACH('Property','Value',...) creates a new TEACH or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before teach_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to teach_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
% Edit the above text to modify the response to help teach
% Last Modified by GUIDE v2.5 21-Dec-2012 16:51:21
global configuration robot
global controls program
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @teach_OpeningFcn, ...
                   'gui_OutputFcn',  @teach_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before teach is made visible.
function teach_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to teach (see VARARGIN)
% Choose default command line output for teach
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes teach wait for user response (see UIRESUME)
% uiwait(handles.figure1);
%initialize application variables
global robot configuration controls targets program
%reset program
program=[];
program.program_counter=0;
program.n_lines=0; %counter for the number of matlab lines
program.rapid_lines=[];
program.matlab_lines=[];
%reset targets
targets=[];
controls.num_target_points=0;
controls.global_gui_handle=hObject;
robot.q=zeros(1,robot.DOF)';
%reset position velocity acceleration and time
robot.q_vector=[];
robot.qd_vector=[];
robot.qdd_vector=[];
robot.time=[];
%update T and Q in the program
update_T_Q()
figure(configuration.figure.robot);
disp('Select the desired view for your robot')
drawrobot3d(robot, robot.q);
% --- Outputs from this function are returned to the command line.
function varargout = teach_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes on selection change in popupmenu_instruction.
function popupmenu_instruction_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_instruction (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_instruction contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_instruction
% --- Executes during object creation, after setting all properties.
function popupmenu_instruction_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_instruction (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global controls
controls.popupmenu_instruction=hObject;
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in listbox1.
function listbox1_Callback(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns listbox1 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox1
% --- Executes during object creation, after setting all properties.
function listbox1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in popupmenu_target_point.
function popupmenu_target_point_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_target_point (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_target_point contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_target_point
% --- Executes during object creation, after setting all properties.
function popupmenu_target_point_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_target_point (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global controls
controls.popupmenu_target_point=hObject;
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in popupmenu_through_point.
function popupmenu_through_point_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_through_point (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_through_point contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_through_point
% --- Executes during object creation, after setting all properties.
function popupmenu_through_point_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_through_point (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global controls
controls.popupmenu_through_point=hObject;
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in popupmenu_speed.
function popupmenu_speed_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_speed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_speed contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_speed
% --- Executes during object creation, after setting all properties.
function popupmenu_speed_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_speed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global controls
controls.popupmenu_speed=hObject;
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in pushbutton1.
function pushbutton1_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on selection change in popupmenu_precision.
function popupmenu_precision_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_precision (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_precision contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_precision
% --- Executes during object creation, after setting all properties.
function popupmenu_precision_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_precision (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global controls
controls.popupmenu_precision=hObject;
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on slider movement.
function slider_q1_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q1, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(1)=='R'
    robot.q(1) = slider_value*pi/180;%rad
else
    robot.q(1) = slider_value;%m
end
update_T_Q();
figure(configuration.figure.robot);
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q1=hObject;
if robot.DOF>0
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(1,1)*180/pi,'Max',robot.maxangle(1,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on slider movement.
function slider_q2_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q2, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(2)=='R'
    robot.q(2) = slider_value*pi/180;%rad
else
    robot.q(2) = slider_value;%m
end
update_T_Q();
figure(configuration.figure.robot);
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q2=hObject;
if robot.DOF>1
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(2,1)*180/pi,'Max',robot.maxangle(2,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    %make the control disappear
     set(hObject, 'Min',0,'Max',0, 'Value',0);
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on slider movement.
function slider_q3_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q3, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(3)=='R'
    robot.q(3) = slider_value*pi/180;%rad
else
    robot.q(3) = slider_value;%m
end
figure(configuration.figure.robot);
update_T_Q();
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q3=hObject;
if robot.DOF>2
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(3,1)*180/pi,'Max',robot.maxangle(3,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    %make the control disappear
     set(hObject, 'Min',0,'Max',0, 'Value',0);
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on slider movement.
function slider_q4_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q4, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(4)=='R'
    robot.q(4) = slider_value*pi/180;%rad
else
    robot.q(4) = slider_value;%m
end
update_T_Q();
figure(configuration.figure.robot);
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q4=hObject;
if robot.DOF>3
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(4,1)*180/pi,'Max',robot.maxangle(4,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    %make the control disappear
     set(hObject, 'Min',0,'Max',0, 'Value',0);
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on slider movement.
function slider_q5_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q5, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(5)=='R'
    robot.q(5) = slider_value*pi/180;%rad
else
    robot.q(5) = slider_value;%m
end
update_T_Q();
figure(configuration.figure.robot);
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q5_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q5=hObject;
if robot.DOF>4
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(5,1)*180/pi,'Max',robot.maxangle(5,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    %make the control disappear
     set(hObject, 'Min',0,'Max',0, 'Value',0);
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on slider movement.
function slider_q6_Callback(hObject, eventdata, handles)
% hObject    handle to slider_q6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
global configuration robot controls
slider_value = get(hObject,'Value');
set(controls.edit_q6, 'String', num2str(slider_value));
%convert to rads and store
if robot.kind(6)=='R'
    robot.q(6) = slider_value*pi/180;%rad
else
    robot.q(6) = slider_value;%m
end
update_T_Q();
figure(configuration.figure.robot);
drawrobot3d(robot, robot.q);
draw_target_points();
% --- Executes during object creation, after setting all properties.
function slider_q6_CreateFcn(hObject, eventdata, handles)
% hObject    handle to slider_q6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
global robot controls
controls.slider_q6=hObject;
if robot.DOF>5
    %modify the limits of the slider object to fit max and min limits
    set(hObject, 'Min',robot.maxangle(6,1)*180/pi,'Max',robot.maxangle(6,2)*180/pi, 'Value',0,'SliderStep',[0.005 0.2]);
else
    %make the control disappear
     set(hObject, 'Min',0,'Max',0, 'Value',0);
    disp('\nPlease set robot.DOF correspondingly')
end
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on button press in pushbutton_x_minus.
function pushbutton_x_minus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_x_minus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%FIND RESOLUTION OF MOVEMENT
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(1) = P_ini(1) - delta;
    else %move in end effector's coordinates
        P_final = P_ini - delta*T(1:3,1);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [1    0          0        0;
        0 cos(-delta) -sin(-delta) 0;
        0  sin(-delta) cos(-delta) 0;
        0   0              0     1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
    else %move in end effector's coordinates
        T_final = T*Trot;
    end
    ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
    conf=compute_configuration(robot, robot.q);
    %convert to quaternion
    Q = T2quaternion(T_final);
    Q=real(Q);
    tp=[[P_ini'],[Q],conf,ejes_ext];
    command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
    eval(command);
end
update_T_Q();
update_sliders();
draw_target_points();
% --- Executes on button press in pushbutton_x_plus.
function pushbutton_x_plus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_x_plus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%substract this quantity to X in base coordinates
%compute total movement
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(1) = P_ini(1) + delta;
    else %move in end effector's coordinates
        P_final = P_ini + delta*T(1:3,1);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [1    0          0        0;
        0 cos(delta) -sin(delta) 0;
        0  sin(delta) cos(delta) 0;
        0   0              0     1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
    else %move in end effector's coordinates
        T_final = T*Trot;
    end
    ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
    conf=compute_configuration(robot, robot.q);
    %convert to quaternion
    Q = T2quaternion(T_final);
    Q=real(Q);
    tp=[[P_ini'],[Q],conf,ejes_ext];
    command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
    eval(command);
end
update_T_Q();
update_sliders();
draw_target_points();
% --- Executes on button press in pushbutton_y_plus.
function pushbutton_y_plus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_y_plus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%substract this quantity to X in base coordinates
%compute total movement
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(2) = P_ini(2) + delta;
    else %move in end effector's coordinates
        P_final = P_ini + delta*T(1:3,2);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [cos(delta)    0          sin(delta)        0;
            0             1            0                0;
            -sin(delta)   0          cos(delta)         0;
            0             0              0               1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
    else %move in end effector's coordinates
        T_final = T*Trot;
    end
    ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
    conf=compute_configuration(robot, robot.q);
    %convert to quaternion
    Q = T2quaternion(T_final);
    Q=real(Q);
    tp=[[P_ini'],[Q],conf,ejes_ext];
    command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
    eval(command);
end
update_T_Q();
update_sliders();
draw_target_points();
% --- Executes on button press in pushbutton_y_minus.
function pushbutton_y_minus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_y_minus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%substract this quantity to X in base coordinates
%compute total movement
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(2) = P_ini(2) - delta;
    else %move in end effector's coordinates
        P_final = P_ini - delta*T(1:3,2);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [cos(-delta)    0          sin(-delta)        0;
            0             1            0                0;
            -sin(-delta)   0          cos(-delta)         0;
            0             0              0               1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
    else %move in end effector's coordinates
        T_final = T*Trot;
    end
    ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
    conf=compute_configuration(robot, robot.q);
    %convert to quaternion
    Q = T2quaternion(T_final);
    Q=real(Q);
    tp=[[P_ini'],[Q],conf,ejes_ext];
    command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
    eval(command);
end
update_T_Q();
update_sliders();
draw_target_points();
% --- Executes on button press in pushbutton_z_plus.
function pushbutton_z_plus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_z_plus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%substract this quantity to X in base coordinates
%compute total movement
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(3) = P_ini(3) + delta;
    else %move in end effector's coordinates
        P_final = P_ini + delta*T(1:3,3);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [cos(delta)       -sin(delta)          0     0;
            sin(delta)         cos(delta)         0     0;
                0                  0              1     0;
                0                   0              0    1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
    else %move in end effector's coordinates
        T_final = T*Trot;
    end
    ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
    conf=compute_configuration(robot, robot.q);
    %convert to quaternion
    Q = T2quaternion(T_final);
    Q=real(Q);
    tp=[[P_ini'],[Q],conf,ejes_ext];
    command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
    eval(command);
end
update_T_Q();
update_sliders();
draw_target_points();
% --- Executes on button press in pushbutton_z_minus.
function pushbutton_z_minus_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_z_minus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global robot controls
%substract this quantity to X in base coordinates
%compute total movement
resolution=get(controls.popupmenu_resolution,'Value');
if resolution==3 %low
    delta=0.001; %m
end
if resolution==2
    delta=0.1; %m
end
if resolution==1
    delta=0.2; %m
end
T = directkinematic(robot, robot.q);
P_ini=T(1:3,4);
% FIND KIND OF MOVEMENT, LINES OR REORIENTATION
line_reorient=get(controls.popupmenu_line_reorient,'Value');
% MOVE IN LINES
if line_reorient==1
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        P_final = P_ini;
        P_final(3) = P_ini(3) - delta;
    else %move in end effector's coordinates
        P_final = P_ini - delta*T(1:3,3);
    end
    follow_line(P_ini,P_final);
else% REORIENTATION
    %compute objective T with rotation
    Trot = [cos(-delta)       -sin(-delta)          0     0;
            sin(-delta)         cos(-delta)         0     0;
                0                  0              1     0;
                0                   0              0    1];
    base=get(controls.popupmenu_base_end,'Value');
    if base==1 %move in base coordinates
        T_final = Trot*T;
1000     else %move in end effector's coordinates
1001         T_final = T*Trot;
1002     end
1003
1004     ejes_ext = [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09];
1005     conf=compute_configuration(robot, robot.q);
1006
1007
1008     %convert to quaternion
1009     Q = T2quaternion(T_final);
1010     Q=real(Q);
1011     tp=[[P_ini'],[Q],conf,ejes_ext];
1012
1013     command =['[robot] = MoveL(robot,tp,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
1014     eval(command);
1015 end
1016
1017 update_T_Q();
1018 update_sliders();
1019 draw_target_points();
1020
1021
1022 function edit_q1_Callback(hObject, eventdata, handles)
1023 % hObject    handle to edit_q1 (see GCBO)
1024 % eventdata  reserved - to be defined in a future version of MATLAB
1025 % handles    structure with handles and user data (see GUIDATA)
1026
1027 % Hints: get(hObject,'String') returns contents of edit_q1 as text
1028 %        str2double(get(hObject,'String')) returns contents of edit_q1 as a double
1029
1030
1031 % --- Executes during object creation, after setting all properties.
1032 function edit_q1_CreateFcn(hObject, eventdata, handles)
1033 % hObject    handle to edit_q1 (see GCBO)
1034 % eventdata  reserved - to be defined in a future version of MATLAB
1035 % handles    empty - handles not created until after all CreateFcns called
1036
1037 global controls
1038
1039 %save the control so that it can be accessed elsewhere
1040 controls.edit_q1=hObject;
1041
1042 % Hint: edit controls usually have a white background on Windows.
1043 %       See ISPC and COMPUTER.
1044 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1045     set(hObject,'BackgroundColor','white');
1046
1047 end
1048
1049 %set(hObject, 'String', 'Push button pushed')
1050
1051 function edit_q2_Callback(hObject, eventdata, handles)
1052 % hObject    handle to edit_q2 (see GCBO)
1053 % eventdata  reserved - to be defined in a future version of MATLAB
1054 % handles    structure with handles and user data (see GUIDATA)
1055
1056 % Hints: get(hObject,'String') returns contents of edit_q2 as text
1057 %        str2double(get(hObject,'String')) returns contents of edit_q2 as a double
1058
1059
1060 % --- Executes during object creation, after setting all properties.
1061 function edit_q2_CreateFcn(hObject, eventdata, handles)
1062 % hObject    handle to edit_q2 (see GCBO)
1063 % eventdata  reserved - to be defined in a future version of MATLAB
1064 % handles    empty - handles not created until after all CreateFcns called
1065
1066 global controls
1067
1068 %save the control so that it can be accessed elsewhere
1069 controls.edit_q2=hObject;
1070
1071 % Hint: edit controls usually have a white background on Windows.
1072 %       See ISPC and COMPUTER.
1073 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1074     set(hObject,'BackgroundColor','white');
1075 end
1076
1077
1078
1079 function edit_q3_Callback(hObject, eventdata, handles)
1080 % hObject    handle to edit_q3 (see GCBO)
1081 % eventdata  reserved - to be defined in a future version of MATLAB
1082 % handles    structure with handles and user data (see GUIDATA)
1083
1084 % Hints: get(hObject,'String') returns contents of edit_q3 as text
1085 %        str2double(get(hObject,'String')) returns contents of edit_q3 as a double
1086
1087
1088
1089 % --- Executes during object creation, after setting all properties.
1090 function edit_q3_CreateFcn(hObject, eventdata, handles)
1091 % hObject    handle to edit_q3 (see GCBO)
1092 % eventdata  reserved - to be defined in a future version of MATLAB
1093 % handles    empty - handles not created until after all CreateFcns called
1094
1095 global controls
1096
1097 %save the control so that it can be accessed elsewhere
1098 controls.edit_q3=hObject;
1099
1100 % Hint: edit controls usually have a white background on Windows.
1101 %       See ISPC and COMPUTER.
1102 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1103     set(hObject,'BackgroundColor','white');
1104 end
1105
1106
1107
1108 function edit_q4_Callback(hObject, eventdata, handles)
1109 % hObject    handle to edit_q4 (see GCBO)
1110 % eventdata  reserved - to be defined in a future version of MATLAB
1111 % handles    structure with handles and user data (see GUIDATA)
1112
1113 % Hints: get(hObject,'String') returns contents of edit_q4 as text
1114 %        str2double(get(hObject,'String')) returns contents of edit_q4 as a double
1115
1116
1117 % --- Executes during object creation, after setting all properties.
1118 function edit_q4_CreateFcn(hObject, eventdata, handles)
1119 % hObject    handle to edit_q4 (see GCBO)
1120 % eventdata  reserved - to be defined in a future version of MATLAB
1121 % handles    empty - handles not created until after all CreateFcns called
1122
1123
1124 global controls
1125
1126 %save the control so that it can be accessed elsewhere
1127 controls.edit_q4=hObject;
1128
1129 % Hint: edit controls usually have a white background on Windows.
1130 %       See ISPC and COMPUTER.
1131 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1132     set(hObject,'BackgroundColor','white');
1133 end
1134
1135
1136
1137 function edit_q5_Callback(hObject, eventdata, handles)
1138 % hObject    handle to edit_q5 (see GCBO)
1139 % eventdata  reserved - to be defined in a future version of MATLAB
1140 % handles    structure with handles and user data (see GUIDATA)
1141
1142 % Hints: get(hObject,'String') returns contents of edit_q5 as text
1143 %        str2double(get(hObject,'String')) returns contents of edit_q5 as a double
1144
1145
1146 % --- Executes during object creation, after setting all properties.
1147 function edit_q5_CreateFcn(hObject, eventdata, handles)
1148 % hObject    handle to edit_q5 (see GCBO)
1149 % eventdata  reserved - to be defined in a future version of MATLAB
1150 % handles    empty - handles not created until after all CreateFcns called
1151
1152
1153 global controls
1154
1155 %save the control so that it can be accessed elsewhere
1156 controls.edit_q5=hObject;
1157
1158 % Hint: edit controls usually have a white background on Windows.
1159 %       See ISPC and COMPUTER.
1160 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1161     set(hObject,'BackgroundColor','white');
1162 end
1163
1164
1165
1166 function edit_q6_Callback(hObject, eventdata, handles)
1167 % hObject    handle to edit_q6 (see GCBO)
1168 % eventdata  reserved - to be defined in a future version of MATLAB
1169 % handles    structure with handles and user data (see GUIDATA)
1170
1171 % Hints: get(hObject,'String') returns contents of edit_q6 as text
1172 %        str2double(get(hObject,'String')) returns contents of edit_q6 as a double
1173
1174
1175 % --- Executes during object creation, after setting all properties.
1176 function edit_q6_CreateFcn(hObject, eventdata, handles)
1177 % hObject    handle to edit_q6 (see GCBO)
1178 % eventdata  reserved - to be defined in a future version of MATLAB
1179 % handles    empty - handles not created until after all CreateFcns called
1180
1181
1182 global controls
1183
1184 %save the control so that it can be accessed elsewhere
1185 controls.edit_q6=hObject;
1186
1187 % Hint: edit controls usually have a white background on Windows.
1188 %       See ISPC and COMPUTER.
1189 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1190     set(hObject,'BackgroundColor','white');
1191 end
1192
1193
1194 % --- Executes on button press in pushbutton_load.
1195 function pushbutton_load_Callback(hObject, eventdata, handles)
1196 % hObject    handle to pushbutton_load (see GCBO)
1197 % eventdata  reserved - to be defined in a future version of MATLAB
1198 % handles    structure with handles and user data (see GUIDATA)
1199
1200 global program controls targets robot
1201
1202 program=[];
1203
1204 %always require a filename
1205 [filename, pathname] = uigetfile('*.m','Select .m program to load');
1206 if isequal(filename,0)
1207    disp('User selected Cancel')
1208    return;
1209 else
1210    disp(['User selected', fullfile(pathname, filename)])
1211 end
1212
1213
1214 %open selected file for read only
1215 fp=fopen(fullfile(pathname, filename),'r');
1216
1217 disp('Loading target points');
1218 while 1
1219     a = fgets(fp);
1220     k = strfind(a, '%BEGINTARGETPOINTS');
1221
1222     %find beginning of target points
1223     if k>=0
1224         break;
1225     end
1226 end
1227
1228 target_names=[];
1229 %reset number of target points
1230 N=0;
1231 %now load target points
1232 while 1
1233     a = fgets(fp);
1234     if length(a)<=1
1235         continue;
1236     end
1237     k = strfind(a, '%ENDTARGETPOINTS');
1238     %test whether there are no more target points
1239     if k>=0
1240         break;
1241     end
1242
1243     %test whether its a valid target point initialization in matlab
1244     k = strfind(a, ':=');
1245     if k>=0
1246         continue;
1247     end
1248
1249     [name, Q, T, conf]=get_targetpoint_from_string(a);
1250
1251     N=N+1;
1252     targets{N}.name=name;
1253     targets{N}.Q=Q;
1254     targets{N}.T=T;
1255     targets{N}.conf=conf;
1256
1257
1258     qinv = inversekinematic(robot, T);
1259     q = select_configuration(robot, qinv, conf);
1260     targets{N}.q=q;
1261
1262     target_names{N}=name;
1263
1264     %store the name in the programming popup storing the available targets.
1265     set(controls.popupmenu_target_point,'String',target_names);
1266     set(controls.popupmenu_through_point,'String',target_names);
1267
1268 end
1269 controls.num_target_points=N;
1270
1271 disp('Loading program');
1272 program.n_lines=0;
1273 %now load program
1274 target_names=[];
1275 %reset number of target points
1276 N=0;
1277 %now load target points
1278 while 1
1279     a = fgets(fp);
1280     if length(a)<=1
1281         continue;
1282     end
1283
1284     k = strfind(a, '%ENDMODULE');
1285     %test whether we reached the end of the program
1286     if k>=0
1287         break;
1288     end
1289
1290     %test whether its a valid target point initialization in matlab
1291     k = strfind(a, '(');
1292     if isempty(k)
1293         continue;
1294     end
1295
1296     N = N+1;
1297
1298     program.n_lines=N;
1299     program.matlab_lines{N}=a(1:end-1); %remove carriage return
1300     %program.rapid_lines{N}=a;
1301 end
1302
1303 fclose(fp);
1304
1305 draw_target_points();
1306
1307
1308 %Save the whole program to a .m file
1309 % --- Executes on button press in pushbutton_save.
1310 function pushbutton_save_Callback(hObject, eventdata, handles)
1311 % hObject    handle to pushbutton_save (see GCBO)
1312 % eventdata  reserved - to be defined in a future version of MATLAB
1313 % handles    structure with handles and user data (see GUIDATA)
1314
1315 global program controls targets
1316
1317 %always require a filename
1318 [filename, pathname] = uiputfile('*.m','Save as .m');
1319 if isequal(filename,0) || isequal(pathname,0)
1320    disp('User selected Cancel')
1321    return;
1322 else
1323    disp(['User selected',fullfile(pathname,filename)])
1324 end
1325
1326
1327 %open selected file
1328 fp=fopen(fullfile(pathname, filename),'w');
1329
1330 disp('Saving target points');
1331
1332 fprintf(fp, '%%BEGINMODULE');
1333 %write two escape characters to
1334 fprintf(fp, '\n%%BEGINTARGETPOINTS');
1335 for i=1:controls.num_target_points,
1336     tp = construct_target(i);
1337     ejes_ext = '[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];';
1338     a_rap = sprintf('%s:=[[%.5f, %.5f, %.5f],[%.5f, %.5f, %.5f, %.5f], [%.5f, %.5f, %.5f, %.5f], %s',...
1339     targets{i}.name, targets{i}.T(1,4),targets{i}.T(2,4),targets{i}.T(3,4),...
1340             targets{i}.Q(1), targets{i}.Q(2), targets{i}.Q(3), targets{i}.Q(4),...
1341         targets{i}.conf(1), targets{i}.conf(2), targets{i}.conf(3), targets{i}.conf(4), ejes_ext);
1342     a_mat = sprintf('%s=[[%.5f, %.5f, %.5f],[%.5f, %.5f, %.5f, %.5f], [%.5f, %.5f, %.5f, %.5f], %s',...
1343     targets{i}.name, targets{i}.T(1,4),targets{i}.T(2,4),targets{i}.T(3,4),...
1344             targets{i}.Q(1), targets{i}.Q(2), targets{i}.Q(3), targets{i}.Q(4),...
1345         targets{i}.conf(1), targets{i}.conf(2), targets{i}.conf(3), targets{i}.conf(4), ejes_ext);
1346     %write file
1347     %fprintf(fp, '\n%%%s', a_rap);
1348     fprintf(fp, '\n%s', a_mat);
1349 end
1350
1351 fprintf(fp, '\n%%ENDTARGETPOINTS\n');
1352
1353
1354 disp('Saving program lines');
1355 for i=1:program.n_lines,
1356     fprintf(fp, '\n%s', program.matlab_lines{i});
1357    % fprintf(fp, '\n%%%s', program.rapid_lines{i});
1358 end
1359
1360 fprintf(fp, '\n%%ENDMODULE\n');
1361 fclose(fp);
1362
1363
1364 % simulate the whole program
1365 % --- Executes on button press in pushbutton_simulate.
1366 function pushbutton_simulate_Callback(hObject, eventdata, handles)
1367 % hObject    handle to pushbutton_simulate (see GCBO)
1368 % eventdata  reserved - to be defined in a future version of MATLAB
1369 % handles    structure with handles and user data (see GUIDATA)
1370
1371 global program targets controls robot
1372
1373 %reset position velocity acceleration and time
1374 robot.q_vector=[];
1375 robot.qd_vector=[];
1376 robot.qdd_vector=[];
1377 robot.time=[];
1378
1379
1380 ejes_ext = '[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];';
1381
1382 for i=1:controls.num_target_points,
1383     a_mat = sprintf('%s=[[%.5f, %.5f, %.5f],[%.5f, %.5f, %.5f, %.5f], [%.5f, %.5f, %.5f, %.5f], %s',...
1384     targets{i}.name, targets{i}.T(1,4),targets{i}.T(2,4),targets{i}.T(3,4),...
1385     targets{i}.Q(1), targets{i}.Q(2), targets{i}.Q(3), targets{i}.Q(4),...
1386     targets{i}.conf(1), targets{i}.conf(2), targets{i}.conf(3), targets{i}.conf(4), ejes_ext);
1387     eval(a_mat);
1388 end
1389
1390 for i=1:program.n_lines,
1391     eval(program.matlab_lines{i});
1392     update_T_Q();
1393     update_sliders();
1394     draw_target_points();
1395 end
1396
1397 robot.q_vector=[];
1398 robot.qd_vector=[];
1399 robot.qdd_vector=[];
1400 robot.time=[];
1401
1402
1403
1404 function edit_nx_Callback(hObject, eventdata, handles)
1405 % hObject    handle to edit_nx (see GCBO)
1406 % eventdata  reserved - to be defined in a future version of MATLAB
1407 % handles    structure with handles and user data (see GUIDATA)
1408
1409 % Hints: get(hObject,'String') returns contents of edit_nx as text
1410 %        str2double(get(hObject,'String')) returns contents of edit_nx as a double
1411
1412
1413 % --- Executes during object creation, after setting all properties.
1414 function edit_nx_CreateFcn(hObject, eventdata, handles)
1415 % hObject    handle to edit_nx (see GCBO)
1416 % eventdata  reserved - to be defined in a future version of MATLAB
1417 % handles    empty - handles not created until after all CreateFcns called
1418 global controls
1419 controls.edit_nx=hObject;
1420 % Hint: edit controls usually have a white background on Windows.
1421 %       See ISPC and COMPUTER.
1422 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1423     set(hObject,'BackgroundColor','white');
1424 end
1425
1426
1427
1428 function edit_ox_Callback(hObject, eventdata, handles)
1429 % hObject    handle to edit_ox (see GCBO)
1430 % eventdata  reserved - to be defined in a future version of MATLAB
1431 % handles    structure with handles and user data (see GUIDATA)
1432
1433 % Hints: get(hObject,'String') returns contents of edit_ox as text
1434 %        str2double(get(hObject,'String')) returns contents of edit_ox as a double
1435
1436
1437 % --- Executes during object creation, after setting all properties.
1438 function edit_ox_CreateFcn(hObject, eventdata, handles)
1439 % hObject    handle to edit_ox (see GCBO)
1440 % eventdata  reserved - to be defined in a future version of MATLAB
1441 % handles    empty - handles not created until after all CreateFcns called
1442 global controls
1443 controls.edit_ox=hObject;
1444 % Hint: edit controls usually have a white background on Windows.
1445 %       See ISPC and COMPUTER.
1446 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1447     set(hObject,'BackgroundColor','white');
1448 end
1449
1450
1451
1452 function edit_ax_Callback(hObject, eventdata, handles)
1453 % hObject    handle to edit_ax (see GCBO)
1454 % eventdata  reserved - to be defined in a future version of MATLAB
1455 % handles    structure with handles and user data (see GUIDATA)
1456
1457 % Hints: get(hObject,'String') returns contents of edit_ax as text
1458 %        str2double(get(hObject,'String')) returns contents of edit_ax as a double
1459
1460
1461 % --- Executes during object creation, after setting all properties.
1462 function edit_ax_CreateFcn(hObject, eventdata, handles)
1463 % hObject    handle to edit_ax (see GCBO)
1464 % eventdata  reserved - to be defined in a future version of MATLAB
1465 % handles    empty - handles not created until after all CreateFcns called
1466 global controls
1467 controls.edit_ax=hObject;
1468 % Hint: edit controls usually have a white background on Windows.
1469 %       See ISPC and COMPUTER.
1470 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1471     set(hObject,'BackgroundColor','white');
1472 end
1473
1474
1475
1476 function edit_pxt_Callback(hObject, eventdata, handles)
1477 % hObject    handle to edit_pxt (see GCBO)
1478 % eventdata  reserved - to be defined in a future version of MATLAB
1479 % handles    structure with handles and user data (see GUIDATA)
1480
1481 % Hints: get(hObject,'String') returns contents of edit_pxt as text
1482 %        str2double(get(hObject,'String')) returns contents of edit_pxt as a double
1483
1484
1485 % --- Executes during object creation, after setting all properties.
1486 function edit_pxt_CreateFcn(hObject, eventdata, handles)
1487 % hObject    handle to edit_pxt (see GCBO)
1488 % eventdata  reserved - to be defined in a future version of MATLAB
1489 % handles    empty - handles not created until after all CreateFcns called
1490 global controls
1491 controls.edit_pxt=hObject;
1492 % Hint: edit controls usually have a white background on Windows.
1493 %       See ISPC and COMPUTER.
1494 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1495     set(hObject,'BackgroundColor','white');
1496 end
1497
1498
1499
1500 function edit_ny_Callback(hObject, eventdata, handles)
1501 % hObject    handle to edit_ny (see GCBO)
1502 % eventdata  reserved - to be defined in a future version of MATLAB
1503 % handles    structure with handles and user data (see GUIDATA)
1504
1505 % Hints: get(hObject,'String') returns contents of edit_ny as text
1506 %        str2double(get(hObject,'String')) returns contents of edit_ny as a double
1507
1508
1509 % --- Executes during object creation, after setting all properties.
1510 function edit_ny_CreateFcn(hObject, eventdata, handles)
1511 % hObject    handle to edit_ny (see GCBO)
1512 % eventdata  reserved - to be defined in a future version of MATLAB
1513 % handles    empty - handles not created until after all CreateFcns called
1514 global controls
1515 controls.edit_ny=hObject;
1516 % Hint: edit controls usually have a white background on Windows.
1517 %       See ISPC and COMPUTER.
1518 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1519     set(hObject,'BackgroundColor','white');
1520 end
1521
1522
1523
1524 function edit_oy_Callback(hObject, eventdata, handles)
1525 % hObject    handle to edit_oy (see GCBO)
1526 % eventdata  reserved - to be defined in a future version of MATLAB
1527 % handles    structure with handles and user data (see GUIDATA)
1528
1529 % Hints: get(hObject,'String') returns contents of edit_oy as text
1530 %        str2double(get(hObject,'String')) returns contents of edit_oy as a double
1531
1532
1533 % --- Executes during object creation, after setting all properties.
1534 function edit_oy_CreateFcn(hObject, eventdata, handles)
1535 % hObject    handle to edit_oy (see GCBO)
1536 % eventdata  reserved - to be defined in a future version of MATLAB
1537 % handles    empty - handles not created until after all CreateFcns called
1538 global controls
1539 controls.edit_oy=hObject;
1540 % Hint: edit controls usually have a white background on Windows.
1541 %       See ISPC and COMPUTER.
1542 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1543     set(hObject,'BackgroundColor','white');
1544 end
1545
1546
1547
1548 function edit_ay_Callback(hObject, eventdata, handles)
1549 % hObject    handle to edit_ay (see GCBO)
1550 % eventdata  reserved - to be defined in a future version of MATLAB
1551 % handles    structure with handles and user data (see GUIDATA)
1552
1553 % Hints: get(hObject,'String') returns contents of edit_ay as text
1554 %        str2double(get(hObject,'String')) returns contents of edit_ay as a double
1555
1556
1557 % --- Executes during object creation, after setting all properties.
1558 function edit_ay_CreateFcn(hObject, eventdata, handles)
1559 % hObject    handle to edit_ay (see GCBO)
1560 % eventdata  reserved - to be defined in a future version of MATLAB
1561 % handles    empty - handles not created until after all CreateFcns called
1562 global controls
1563 controls.edit_ay=hObject;
1564 % Hint: edit controls usually have a white background on Windows.
1565 %       See ISPC and COMPUTER.
1566 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1567     set(hObject,'BackgroundColor','white');
1568 end
1569
1570
1571
1572 function edit_pyt_Callback(hObject, eventdata, handles)
1573 % hObject    handle to edit_pyt (see GCBO)
1574 % eventdata  reserved - to be defined in a future version of MATLAB
1575 % handles    structure with handles and user data (see GUIDATA)
1576
1577 % Hints: get(hObject,'String') returns contents of edit_pyt as text
1578 %        str2double(get(hObject,'String')) returns contents of edit_pyt as a double
1579
1580
1581 % --- Executes during object creation, after setting all properties.
1582 function edit_pyt_CreateFcn(hObject, eventdata, handles)
1583 % hObject    handle to edit_pyt (see GCBO)
1584 % eventdata  reserved - to be defined in a future version of MATLAB
1585 % handles    empty - handles not created until after all CreateFcns called
1586 global controls
1587 controls.edit_pyt=hObject;
1588 % Hint: edit controls usually have a white background on Windows.
1589 %       See ISPC and COMPUTER.
1590 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1591     set(hObject,'BackgroundColor','white');
1592 end
1593
1594
1595
1596 function edit_nz_Callback(hObject, eventdata, handles)
1597 % hObject    handle to edit_nz (see GCBO)
1598 % eventdata  reserved - to be defined in a future version of MATLAB
1599 % handles    structure with handles and user data (see GUIDATA)
1600
1601 % Hints: get(hObject,'String') returns contents of edit_nz as text
1602 %        str2double(get(hObject,'String')) returns contents of edit_nz as a double
1603
1604
1605 % --- Executes during object creation, after setting all properties.
1606 function edit_nz_CreateFcn(hObject, eventdata, handles)
1607 % hObject    handle to edit_nz (see GCBO)
1608 % eventdata  reserved - to be defined in a future version of MATLAB
1609 % handles    empty - handles not created until after all CreateFcns called
1610 global controls
1611 controls.edit_nz=hObject;
1612 % Hint: edit controls usually have a white background on Windows.
1613 %       See ISPC and COMPUTER.
1614 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1615     set(hObject,'BackgroundColor','white');
1616 end
1617
1618
1619
1620 function edit_oz_Callback(hObject, eventdata, handles)
1621 % hObject    handle to edit_oz (see GCBO)
1622 % eventdata  reserved - to be defined in a future version of MATLAB
1623 % handles    structure with handles and user data (see GUIDATA)
1624
1625 % Hints: get(hObject,'String') returns contents of edit_oz as text
1626 %        str2double(get(hObject,'String')) returns contents of edit_oz as a double
1627
1628
1629 % --- Executes during object creation, after setting all properties.
1630 function edit_oz_CreateFcn(hObject, eventdata, handles)
1631 % hObject    handle to edit_oz (see GCBO)
1632 % eventdata  reserved - to be defined in a future version of MATLAB
1633 % handles    empty - handles not created until after all CreateFcns called
1634 global controls
1635 controls.edit_oz=hObject;
1636 % Hint: edit controls usually have a white background on Windows.
1637 %       See ISPC and COMPUTER.
1638 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1639     set(hObject,'BackgroundColor','white');
1640 end
1641
1642
1643
1644 function edit_az_Callback(hObject, eventdata, handles)
1645 % hObject    handle to edit_az (see GCBO)
1646 % eventdata  reserved - to be defined in a future version of MATLAB
1647 % handles    structure with handles and user data (see GUIDATA)
1648
1649 % Hints: get(hObject,'String') returns contents of edit_az as text
1650 %        str2double(get(hObject,'String')) returns contents of edit_az as a double
1651
1652
1653 % --- Executes during object creation, after setting all properties.
1654 function edit_az_CreateFcn(hObject, eventdata, handles)
1655 % hObject    handle to edit_az (see GCBO)
1656 % eventdata  reserved - to be defined in a future version of MATLAB
1657 % handles    empty - handles not created until after all CreateFcns called
1658 global controls
1659 controls.edit_az=hObject;
1660 % Hint: edit controls usually have a white background on Windows.
1661 %       See ISPC and COMPUTER.
1662 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1663     set(hObject,'BackgroundColor','white');
1664 end
1665
1666
1667
1668 function edit_pzt_Callback(hObject, eventdata, handles)
1669 % hObject    handle to edit_pzt (see GCBO)
1670 % eventdata  reserved - to be defined in a future version of MATLAB
1671 % handles    structure with handles and user data (see GUIDATA)
1672
1673 % Hints: get(hObject,'String') returns contents of edit_pzt as text
1674 %        str2double(get(hObject,'String')) returns contents of edit_pzt as a double
1675
1676
1677 % --- Executes during object creation, after setting all properties.
1678 function edit_pzt_CreateFcn(hObject, eventdata, handles)
1679 % hObject    handle to edit_pzt (see GCBO)
1680 % eventdata  reserved - to be defined in a future version of MATLAB
1681 % handles    empty - handles not created until after all CreateFcns called
1682 global controls
1683 controls.edit_pzt=hObject;
1684 % Hint: edit controls usually have a white background on Windows.
1685 %       See ISPC and COMPUTER.
1686 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1687     set(hObject,'BackgroundColor','white');
1688 end
1689
1690
1691 % SOLVE THE INVERSE KINEMATIC PROBLEM AND GO TO IT
1692 %   THE CLOSEST CONFIGURATION IS ALWAYS FOUND IN THE JOINT SPACE
1693 % --- Executes on button press in pushbutton_moveT.
1694 function pushbutton_moveT_Callback(hObject, eventdata, handles)
1695 % hObject    handle to pushbutton_moveT (see GCBO)
1696 % eventdata  reserved - to be defined in a future version of MATLAB
1697 % handles    structure with handles and user data (see GUIDATA)
1698
1699
1700 global robot controls configuration
1701
1702 %get values of T from dialog
1703 [T,Q,P]=get_TQ_from_dialog();
1704
1705 %several solutions are provided
1706 qinv = inversekinematic(robot, T);
1707
1708 distance_joint=[];
1709 for i=1:size(qinv,2),
1710    distance_joint(i)=sum(abs(qinv(:,i)-robot.q));
1711 end
1712 [val,i]=min(distance_joint);
1713
1714 q_current=robot.q;
1715 q_final = qinv(:,i);
1716
1717 path = lineal_path_plan(q_current, q_final);
1718
1719 robot.q_vector=path;
1720 %Test whether there are joints outside mechanical limits
1721 test_joint_limits(robot);
1722
1723 %do not move if current and final coordinates are the same
1724 for i=1:size(path,2),
1725    drawrobot3d(robot, path(:,i));
1726    pause(configuration.time_delay);
1727 end
1728
1729 robot.q=q_final;
1730 update_T_Q();
1731 update_sliders();
1732 draw_target_points()
1733
1734 function edit_Q0_Callback(hObject, eventdata, handles)
1735 % hObject    handle to edit_Q0 (see GCBO)
1736 % eventdata  reserved - to be defined in a future version of MATLAB
1737 % handles    structure with handles and user data (see GUIDATA)
1738
1739 % Hints: get(hObject,'String') returns contents of edit_Q0 as text
1740 %        str2double(get(hObject,'String')) returns contents of edit_Q0 as a double
1741
1742
1743 % --- Executes during object creation, after setting all properties.
1744 function edit_Q0_CreateFcn(hObject, eventdata, handles)
1745 % hObject    handle to edit_Q0 (see GCBO)
1746 % eventdata  reserved - to be defined in a future version of MATLAB
1747 % handles    empty - handles not created until after all CreateFcns called
1748 global controls
1749 controls.edit_Q0=hObject;
1750 % Hint: edit controls usually have a white background on Windows.
1751 %       See ISPC and COMPUTER.
1752 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1753     set(hObject,'BackgroundColor','white');
1754 end
1755
1756
1757
1758 function edit_Q1_Callback(hObject, eventdata, handles)
1759 % hObject    handle to edit_Q1 (see GCBO)
1760 % eventdata  reserved - to be defined in a future version of MATLAB
1761 % handles    structure with handles and user data (see GUIDATA)
1762
1763 % Hints: get(hObject,'String') returns contents of edit_Q1 as text
1764 %        str2double(get(hObject,'String')) returns contents of edit_Q1 as a double
1765
1766
1767 % --- Executes during object creation, after setting all properties.
1768 function edit_Q1_CreateFcn(hObject, eventdata, handles)
1769 % hObject    handle to edit_Q1 (see GCBO)
1770 % eventdata  reserved - to be defined in a future version of MATLAB
1771 % handles    empty - handles not created until after all CreateFcns called
1772 global controls
1773 controls.edit_Q1=hObject;
1774 % Hint: edit controls usually have a white background on Windows.
1775 %       See ISPC and COMPUTER.
1776 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1777     set(hObject,'BackgroundColor','white');
1778 end
1779
1780
1781
1782 function edit_Q2_Callback(hObject, eventdata, handles)
1783 % hObject    handle to edit_Q2 (see GCBO)
1784 % eventdata  reserved - to be defined in a future version of MATLAB
1785 % handles    structure with handles and user data (see GUIDATA)
1786
1787 % Hints: get(hObject,'String') returns contents of edit_Q2 as text
1788 %        str2double(get(hObject,'String')) returns contents of edit_Q2 as a double
1789
1790
1791 % --- Executes during object creation, after setting all properties.
1792 function edit_Q2_CreateFcn(hObject, eventdata, handles)
1793 % hObject    handle to edit_Q2 (see GCBO)
1794 % eventdata  reserved - to be defined in a future version of MATLAB
1795 % handles    empty - handles not created until after all CreateFcns called
1796 global controls
1797 controls.edit_Q2=hObject;
1798 % Hint: edit controls usually have a white background on Windows.
1799 %       See ISPC and COMPUTER.
1800 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1801     set(hObject,'BackgroundColor','white');
1802 end
1803
1804
1805
1806 function edit_Q3_Callback(hObject, eventdata, handles)
1807 % hObject    handle to edit_Q3 (see GCBO)
1808 % eventdata  reserved - to be defined in a future version of MATLAB
1809 % handles    structure with handles and user data (see GUIDATA)
1810
1811 % Hints: get(hObject,'String') returns contents of edit_Q3 as text
1812 %        str2double(get(hObject,'String')) returns contents of edit_Q3 as a double
1813
1814
1815 % --- Executes during object creation, after setting all properties.
1816 function edit_Q3_CreateFcn(hObject, eventdata, handles)
1817 % hObject    handle to edit_Q3 (see GCBO)
1818 % eventdata  reserved - to be defined in a future version of MATLAB
1819 % handles    empty - handles not created until after all CreateFcns called
1820 global controls
1821 controls.edit_Q3=hObject;
1822 % Hint: edit controls usually have a white background on Windows.
1823 %       See ISPC and COMPUTER.
1824 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1825     set(hObject,'BackgroundColor','white');
1826 end
1827
1828
1829
1830 function edit_pxq_Callback(hObject, eventdata, handles)
1831 % hObject    handle to edit_pxq (see GCBO)
1832 % eventdata  reserved - to be defined in a future version of MATLAB
1833 % handles    structure with handles and user data (see GUIDATA)
1834
1835 % Hints: get(hObject,'String') returns contents of edit_pxq as text
1836 %        str2double(get(hObject,'String')) returns contents of edit_pxq as a double
1837
1838
1839 % --- Executes during object creation, after setting all properties.
1840 function edit_pxq_CreateFcn(hObject, eventdata, handles)
1841 % hObject    handle to edit_pxq (see GCBO)
1842 % eventdata  reserved - to be defined in a future version of MATLAB
1843 % handles    empty - handles not created until after all CreateFcns called
1844 global controls
1845 controls.edit_pxq=hObject;
1846 % Hint: edit controls usually have a white background on Windows.
1847 %       See ISPC and COMPUTER.
1848 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1849     set(hObject,'BackgroundColor','white');
1850 end
1851
1852
1853
1854 function edit_pyq_Callback(hObject, eventdata, handles)
1855 % hObject    handle to edit_pyq (see GCBO)
1856 % eventdata  reserved - to be defined in a future version of MATLAB
1857 % handles    structure with handles and user data (see GUIDATA)
1858
1859 % Hints: get(hObject,'String') returns contents of edit_pyq as text
1860 %        str2double(get(hObject,'String')) returns contents of edit_pyq as a double
1861
1862
1863 % --- Executes during object creation, after setting all properties.
1864 function edit_pyq_CreateFcn(hObject, eventdata, handles)
1865 % hObject    handle to edit_pyq (see GCBO)
1866 % eventdata  reserved - to be defined in a future version of MATLAB
1867 % handles    empty - handles not created until after all CreateFcns called
1868 global controls
1869 controls.edit_pyq=hObject;
1870 % Hint: edit controls usually have a white background on Windows.
1871 %       See ISPC and COMPUTER.
1872 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1873     set(hObject,'BackgroundColor','white');
1874 end
1875
1876
1877
1878 function edit_pzq_Callback(hObject, eventdata, handles)
1879 % hObject    handle to edit_pzq (see GCBO)
1880 % eventdata  reserved - to be defined in a future version of MATLAB
1881 % handles    structure with handles and user data (see GUIDATA)
1882
1883 % Hints: get(hObject,'String') returns contents of edit_pzq as text
1884 %        str2double(get(hObject,'String')) returns contents of edit_pzq as a double
1885
1886
1887 % --- Executes during object creation, after setting all properties.
1888 function edit_pzq_CreateFcn(hObject, eventdata, handles)
1889 % hObject    handle to edit_pzq (see GCBO)
1890 % eventdata  reserved - to be defined in a future version of MATLAB
1891 % handles    empty - handles not created until after all CreateFcns called
1892 global controls
1893 controls.edit_pzq=hObject;
1894 % Hint: edit controls usually have a white background on Windows.
1895 %       See ISPC and COMPUTER.
1896 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1897     set(hObject,'BackgroundColor','white');
1898 end
1899
1900
1901
1902 %when pressed, OBTAIN Q from dialog, convert to homogeneous matrix and
1903 %plan a coordinated path to it
1904 % --- Executes on button press in pushbutton_moveQ.
1905 function pushbutton_moveQ_Callback(hObject, eventdata, handles)
1906 % hObject    handle to pushbutton_moveQ (see GCBO)
1907 % eventdata  reserved - to be defined in a future version of MATLAB
1908 % handles    structure with handles and user data (see GUIDATA)
1909
1910
1911 global robot controls configuration
1912
1913 %get values of T from dialog
1914 [T,Q,P]=get_TQ_from_dialog();
1915
1916 %convert quaternion to orientation
1917 T = quaternion2T(Q);
1918
1919 T(1,4)=P(1);
1920 T(2,4)=P(2);
1921 T(3,4)=P(3);
1922
1923 %several solutions are provided
1924 qinv = inversekinematic(robot, T);
1925
1926 distance_joint=[];
1927 for i=1:size(qinv,2),
1928    distance_joint(i)=sum(abs(qinv(:,i)-robot.q));
1929 end
1930 [val,i]=min(distance_joint);
1931
1932 q_current=robot.q;
1933 q_final = qinv(:,i);
1934
1935 path = lineal_path_plan(q_current, q_final);
1936
1937 robot.q_vector=path;
1938 %Test whether there are joints outside mechanical limits
1939 test_joint_limits(robot);
1940
1941 %do not move if current and final coordinates are the same
1942 for i=1:size(path,2),
1943     drawrobot3d(robot, path(:,i));
1944     pause(configuration.time_delay);
1945 end
1946
1947 robot.q=q_final;
1948 update_T_Q();
1949 update_sliders();
1950 draw_target_points()
1951
1952
1953
1954 %save a target point to memory
1955 % --- Executes on button press in pushbutton_save_target_point.
1956 function pushbutton_save_target_point_Callback(hObject, eventdata, handles)
1957 % hObject    handle to pushbutton_save_target_point (see GCBO)
1958 % eventdata  reserved - to be defined in a future version of MATLAB
1959 % handles    structure with handles and user data (see GUIDATA)
1960 global controls robot targets
1961
1962 target_point_name = get(controls.edit_target_point,'String');
1963
1964 %add a target point
1965 controls.num_target_points = controls.num_target_points+1;
1966
1967 T = directkinematic(robot, robot.q);
1968
1969 %convert to quaternion
1970 Q = T2quaternion(T);
1971 Q=real(Q);
1972 target.T = T;
1973 target.Q = Q;
1974 target.q = robot.q;%store the current coordinates
1975 target.conf = compute_configuration(robot, robot.q);
1976 target.name = target_point_name;
1977
1978
1979 targets{controls.num_target_points}=target;
1980 draw_target_points();
1981
1982 s0=get(controls.popupmenu_target_point,'String');
1983 a=length(s0);
1984 s0{a+1}=target_point_name;
1985
1986 %store the name in the programming popup storing the available targets.
1987 set(controls.popupmenu_target_point,'String',s0);
1988
1989
1990 %the through point popupmenu
1991 s0=get(controls.popupmenu_through_point,'String');
1992 a=length(s0);
1993 s0{a+1}=target_point_name;
1994
1995 %store the name in the programming popup storing the available targets.
1996 set(controls.popupmenu_through_point,'String',s0);
1997
1998
1999
2000 function edit_target_point_Callback(hObject, eventdata, handles)
2001 % hObject    handle to edit_target_point (see GCBO)
2002 % eventdata  reserved - to be defined in a future version of MATLAB
2003 % handles    structure with handles and user data (see GUIDATA)
2004
2005 % Hints: get(hObject,'String') returns contents of edit_target_point as text
2006 %        str2double(get(hObject,'String')) returns contents of edit_target_point as a double
2007
2008
2009 % --- Executes during object creation, after setting all properties.
2010 function edit_target_point_CreateFcn(hObject, eventdata, handles)
2011 % hObject    handle to edit_target_point (see GCBO)
2012 % eventdata  reserved - to be defined in a future version of MATLAB
2013 % handles    empty - handles not created until after all CreateFcns called
2014 global controls
2015 controls.edit_target_point = hObject;
2016
2017 % Hint: edit controls usually have a white background on Windows.
2018 %       See ISPC and COMPUTER.
2019 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2020     set(hObject,'BackgroundColor','white');
2021 end
2022
2023
2024 % --- Executes on selection change in popupmenu6.
2025 function popupmenu6_Callback(hObject, eventdata, handles)
2026 % hObject    handle to popupmenu6 (see GCBO)
2027 % eventdata  reserved - to be defined in a future version of MATLAB
2028 % handles    structure with handles and user data (see GUIDATA)
2029
2030 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu6 contents as cell array
2031 %        contents{get(hObject,'Value')} returns selected item from popupmenu6
2032
2033
2034 % --- Executes during object creation, after setting all properties.
2035 function popupmenu6_CreateFcn(hObject, eventdata, handles)
2036 % hObject    handle to popupmenu6 (see GCBO)
2037 % eventdata  reserved - to be defined in a future version of MATLAB
2038 % handles    empty - handles not created until after all CreateFcns called
2039
2040 % Hint: popupmenu controls usually have a white background on Windows.
2041 %       See ISPC and COMPUTER.
2042 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2043     set(hObject,'BackgroundColor','white');
2044 end
2045
2046
2047 % --- Executes on button press in pushbutton_simulate_instruction.
2048 function pushbutton_simulate_instruction_Callback(hObject, eventdata, handles)
2049 % hObject    handle to pushbutton_simulate_instruction (see GCBO)
2050 % eventdata  reserved - to be defined in a future version of MATLAB
2051 % handles    structure with handles and user data (see GUIDATA)
2052
2053 global controls targets robot
2054
2055 %reset position velocity acceleration and time
2056 robot.q_vector=[];
2057 robot.qd_vector=[];
2058 robot.qdd_vector=[];
2059 robot.time=[];
2060
2061 tool0=[];
2062 wobj0=[];
2063
2064 [instruction_matlab, instruction_rapid, tp1, tp2, joint_coord]=build_instruction_to_eval();
2065 eval(instruction_matlab);
2066 % s = get(controls.popupmenu_instruction,'String');
2067 % i = get(controls.popupmenu_instruction,'Value');
2068 % s1=s{i};
2069 %
2070 % switch s1
2071 %     case {'MoveJ','MoveL'}
2072 %
2073 %         s = get(controls.popupmenu_target_point,'String');
2074 %         target_num = get(controls.popupmenu_target_point,'Value');
2075 %         s2=s{target_num};
2076 %
2077 %         s = get(controls.popupmenu_speed,'String');
2078 %         i = get(controls.popupmenu_speed,'Value');
2079 %         s3=s{i};
2080 %
2081 %         s = get(controls.popupmenu_precision,'String');
2082 %         i = get(controls.popupmenu_precision,'Value');
2083 %         s4=s{i};
2084 %
2085 %         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2086 %
2087 %         tp=construct_target(target_num);
2088 %
2089 %         instruction_matlab = ['robot=' s1 '(robot, tp, s3, s4, tool0, wobj0);'];
2090 %         fprintf('\n**********************************************\n');
2091 %         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2092 %         fprintf('**********************************************\n');
2093 %
2094 %         eval(instruction_matlab);
2095 %
2096 %      case 'MoveAbsJ'
2097 %
2098 %         s = get(controls.popupmenu_target_point,'String');
2099 %         target_num = get(controls.popupmenu_target_point,'Value');
2100 %         s2=s{target_num};
2101 %
2102 %         s = get(controls.popupmenu_speed,'String');
2103 %         i = get(controls.popupmenu_speed,'Value');
2104 %         s3=s{i};
2105 %
2106 %         s = get(controls.popupmenu_precision,'String');
2107 %         i = get(controls.popupmenu_precision,'Value');
2108 %         s4=s{i};
2109 %
2110 %         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2111 %
2112 %
2113 %         joint_coord=[targets{target_num}.q' 1e9, 1e9, 1e9, 1e9, 1e9, 1e9];
2114 %
2115 %         instruction_matlab = ['robot=' s1 '(robot, joint_coord, s3, s4, tool0, wobj0);'];
2116 %         fprintf('\n**********************************************\n');
2117 %         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2118 %         fprintf('**********************************************\n');
2119 %
2120 %         eval(instruction_matlab);
2121 %
2122 %
2123 %     case 'MoveC'
2124 %         s = get(controls.popupmenu_target_point,'String');
2125 %         target_num1 = get(controls.popupmenu_target_point,'Value');
2126 %         s2=s{target_num1};
2127 %
2128 %         s = get(controls.popupmenu_through_point,'String');
2129 %         target_num2 = get(controls.popupmenu_through_point,'Value');
2130 %         s3=s{target_num2};
2131 %
2132 %         s = get(controls.popupmenu_speed,'String');
2133 %         i = get(controls.popupmenu_speed,'Value');
2134 %         vel=s{i};
2135 %
2136 %         s = get(controls.popupmenu_precision,'String');
2137 %         i = get(controls.popupmenu_precision,'Value');
2138 %         prec=s{i};
2139 %
2140 %         instruction_rapid = [s1 ' ' s3 ',' s2 ',' vel ',' prec  ',tool0\Wobj:=wobj0;'];
2141 %
2142 %         tp2=construct_target(target_num1);
2143 %         tp1=construct_target(target_num2);%the through point
2144 %
2145 %         instruction_matlab = ['robot=' s1 '(robot, tp1, tp2, vel , prec);'];
2146 %         fprintf('\n**********************************************\n');
2147 %         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2148 %         fprintf('**********************************************\n');
2149 %
2150 %         eval(instruction_matlab);
2151 %
2152 %     otherwise disp('RAPID instruction not supported');
2153 % end
2154
2155 %reset position velocity acceleration and time
2156 robot.q_vector=[];
2157 robot.qd_vector=[];
2158 robot.qdd_vector=[];
2159 robot.time=[];
2160
2161 update_T_Q();
2162 update_sliders();
2163 draw_target_points();
2164
2165 %clf(controls.global_gui_handle)
2166 %drawnow()
2167
2168
2169 % --- Executes on button press in pushbutton_save_instruction.
2170 function pushbutton_save_instruction_Callback(hObject, eventdata, handles)
2171 % hObject    handle to pushbutton_save_instruction (see GCBO)
2172 % eventdata  reserved - to be defined in a future version of MATLAB
2173 % handles    structure with handles and user data (see GUIDATA)
2174
2175 global controls targets robot program
2176
2177 % %Get instruction name
2178 % instruction = [];
2179 %
2180 % s = get(controls.popupmenu_instruction,'String');
2181 % i = get(controls.popupmenu_instruction,'Value');
2182 % s1=s{i};
2183 %
2184 % s = get(controls.popupmenu_target_point,'String');
2185 % target_num = get(controls.popupmenu_target_point,'Value');
2186 % s2=s{target_num};
2187 %
2188 % s = get(controls.popupmenu_speed,'String');
2189 % i = get(controls.popupmenu_speed,'Value');
2190 % s3=s{i};
2191 %
2192 % s = get(controls.popupmenu_precision,'String');
2193 % i = get(controls.popupmenu_precision,'Value');
2194 % s4=s{i};
2195
2196
2197 [instruction_matlab, instruction_rapid]=build_instruction_to_save();
2198
2199
2200 %program.program_counter = program.program_counter + 1;
2201 program.n_lines = program.n_lines + 1;
2202
2203 program.rapid_lines{program.n_lines} = instruction_rapid;%[s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2204 program.matlab_lines{program.n_lines} = instruction_matlab;%['robot=' s1 '(robot,' s2 ',' sprintf('''%s''', s3) ',' sprintf('''%s''', s4) ');'];
2205
2206
2207 fprintf('\n**********************************************\n');
2208 fprintf('Adding instruction to program.\nCurrent program:');
2209 fprintf('\n**********************************************\n');
2210 for i=1:program.n_lines,
2211     fprintf('\n%s', program.rapid_lines{i});
2212 end
2213 fprintf('\n**********************************************\n');
2214 update_T_Q();
2215 update_sliders();
2216 draw_target_points()
2217
2218
2219
2220
2221
2222 % --- Executes on key press with focus on slider_q1 and none of its controls.
2223 function slider_q1_KeyPressFcn(hObject, eventdata, handles)
2224 % hObject    handle to slider_q1 (see GCBO)
2225 % eventdata  structure with the following fields (see UICONTROL)
2226 %    Key: name of the key that was pressed, in lower case
2227 %    Character: character interpretation of the key(s) that was pressed
2228 %    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
2229 % handles    structure with handles and user data (see GUIDATA)
2230
2231
2232
2233
2234 % --- Executes on selection change in popupmenu_base_end.
2235 function popupmenu_base_end_Callback(hObject, eventdata, handles)
2236 % hObject    handle to popupmenu_base_end (see GCBO)
2237 % eventdata  reserved - to be defined in a future version of MATLAB
2238 % handles    structure with handles and user data (see GUIDATA)
2239
2240 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_base_end contents as cell array
2241 %        contents{get(hObject,'Value')} returns selected item from popupmenu_base_end
2242
2243
2244 % --- Executes during object creation, after setting all properties.
2245 function popupmenu_base_end_CreateFcn(hObject, eventdata, handles)
2246 % hObject    handle to popupmenu_base_end (see GCBO)
2247 % eventdata  reserved - to be defined in a future version of MATLAB
2248 % handles    empty - handles not created until after all CreateFcns called
2249
2250 global controls
2251 controls.popupmenu_base_end=hObject;
2252
2253 % Hint: popupmenu controls usually have a white background on Windows.
2254 %       See ISPC and COMPUTER.
2255 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2256     set(hObject,'BackgroundColor','white');
2257 end
2258
2259
2260
2261
2262 %%%%%%%%%%%%%%%%%%%%%%%%%%
2263 %   REST OF FUNCTIONS TO HELP DIALOGS
2264 %%%%%%%%%%%%%%%%%%%%%%%%%%%%
2265
2266 %update the values from T to the dialog
2267 function update_T_Q()
2268
2269 global robot controls
2270
2271
2272 T = directkinematic(robot, robot.q);
2273
2274 %Update T
2275 set(controls.edit_nx, 'String', num2str(T(1,1), '%.3f'));
2276 set(controls.edit_ny, 'String', num2str(T(2,1), '%.3f'));
2277 set(controls.edit_nz, 'String', num2str(T(3,1), '%.3f'));
2278 set(controls.edit_ox, 'String', num2str(T(1,2), '%.3f'));
2279 set(controls.edit_oy, 'String', num2str(T(2,2), '%.3f'));
2280 set(controls.edit_oz, 'String', num2str(T(3,2), '%.3f'));
2281 set(controls.edit_ax, 'String', num2str(T(1,3), '%.3f'));
2282 set(controls.edit_ay, 'String', num2str(T(2,3), '%.3f'));
2283 set(controls.edit_az, 'String', num2str(T(3,3), '%.3f'));
2284 set(controls.edit_pxt, 'String', num2str(T(1,4), '%.3f'));
2285 set(controls.edit_pyt, 'String', num2str(T(2,4), '%.3f'));
2286 set(controls.edit_pzt, 'String', num2str(T(3,4), '%.3f'));
2287
2288 %convert T to quaternion
2289 Q = T2quaternion(T);
2290 Q=real(Q);
2291 set(controls.edit_Q0, 'String', num2str(Q(1),'%.3f'));
2292 set(controls.edit_Q1, 'String', num2str(Q(2), '%.3f'));
2293 set(controls.edit_Q2, 'String', num2str(Q(3), '%.3f'));
2294 set(controls.edit_Q3, 'String', num2str(Q(4), '%.3f'));
2295 %the same position as in T
2296 set(controls.edit_pxq, 'String', num2str(T(1,4), '%.3f'));
2297 set(controls.edit_pyq, 'String', num2str(T(2,4), '%.3f'));
2298 set(controls.edit_pzq, 'String', num2str(T(3,4), '%.3f'));
2299
2300
2301 %obtain the values of T Q and posittion from
2302 function [T,Q,P]=get_TQ_from_dialog()
2303
2304 global robot controls
2305
2306
2307 T = eye(4);
2308
2309 %Update T
2310 T(1,1)=sscanf(get(controls.edit_nx, 'String'),'%f');
2311 T(2,1)=sscanf(get(controls.edit_ny, 'String'), '%f');
2312 T(3,1)=sscanf(get(controls.edit_nz, 'String'), '%f');
2313 T(1,2)=sscanf(get(controls.edit_ox, 'String'), '%f');
2314 T(2,2)=sscanf(get(controls.edit_oy, 'String'), '%f');
2315 T(3,2)=sscanf(get(controls.edit_oz, 'String'), '%f');
2316 T(1,3)=sscanf(get(controls.edit_ax, 'String'), '%f');
2317 T(2,3)=sscanf(get(controls.edit_ay, 'String'), '%f');
2318 T(3,3)=sscanf(get(controls.edit_az, 'String'), '%f');
2319 T(1,4)=sscanf(get(controls.edit_pxt, 'String'), '%f');
2320 T(2,4)=sscanf(get(controls.edit_pyt, 'String'), '%f');
2321 T(3,4)=sscanf(get(controls.edit_pzt, 'String'), '%f');
2322
2323 Q = zeros(1,4);
2324 Q(1)=sscanf(get(controls.edit_Q0, 'String'),'%f');
2325 Q(2)=sscanf(get(controls.edit_Q1, 'String'),'%f');
2326 Q(3)=sscanf(get(controls.edit_Q2, 'String'),'%f');
2327 Q(4)=sscanf(get(controls.edit_Q3, 'String'),'%f');
2328
2329 P(1)=sscanf(get(controls.edit_pxq, 'String'), '%f');
2330 P(2)=sscanf(get(controls.edit_pyq, 'String'), '%f');
2331 P(3)=sscanf(get(controls.edit_pzq, 'String'), '%f');
2332
2333
2334 %update the position of the sliders as well as the edit boxes associated to
2335 %them
2336 function update_sliders()
2337
2338 global robot controls
2339
2340 error = test_joints(robot, robot.q);
2341
2342 %do not update in case of any joint exceeds its range
2343 if error == 1
2344 return;
2345 end
2346
2347 %Update the sliders
2348 set(controls.slider_q1, 'Value', robot.q(1)*180/pi);
2349 set(controls.slider_q2, 'Value', robot.q(2)*180/pi);
2350 set(controls.slider_q3, 'Value', robot.q(3)*180/pi);
2351 set(controls.slider_q4, 'Value', robot.q(4)*180/pi);
2352 set(controls.slider_q5, 'Value', robot.q(5)*180/pi);
2353 set(controls.slider_q6, 'Value', robot.q(6)*180/pi);
2354
2355 %update the edit controls associated to them
2356 set(controls.edit_q1, 'String', num2str(robot.q(1)*180/pi,3));
2357 set(controls.edit_q2, 'String', num2str(robot.q(2)*180/pi,3));
2358 set(controls.edit_q3, 'String', num2str(robot.q(3)*180/pi,3));
2359 set(controls.edit_q4, 'String', num2str(robot.q(4)*180/pi,3));
2360 set(controls.edit_q5, 'String', num2str(robot.q(5)*180/pi,3));
2361 set(controls.edit_q6, 'String', num2str(robot.q(6)*180/pi,3));
2362
2363
2364
2365 %plan a lineal path interpolating linearly the joint coordinates
2366 function path=lineal_path_plan(q_ini, q_final)
2367
2368 global robot
2369
2370 %make num_points
2371 num_points = 15;
2372
2373 path = [];
2374
2375 for i=1:robot.DOF,
2376     delta = (q_final(i)-q_ini(i))/num_points;
2377     for j=1:num_points-1;
2378         path(i,j)= q_ini(i)+delta*j;
2379     end
2380     path(i,num_points)=q_final(i);
2381 end
2382
2383
2384
2385 %plan a lineal path interpolating linearly the joint coordinates
2386 function path=lineal_path_planXYZ(P_ini, P_final)
2387
2388 global robot
2389
2390 %make num_points
2391 num_points = 5;
2392
2393 path = [];
2394
2395 for i=1:3, %3, X, Y, Z
2396     delta = (P_final(i)-P_ini(i))/num_points;
2397     for j=1:num_points-1;
2398         path(i,j)= P_ini(i)+delta*j;
2399     end
2400     path(i,num_points)=P_final(i);
2401 end
2402
2403
2404
2405 %follow a line in global coordinates
2406 function follow_line(P_ini,P_final)
2407 global robot configuration
2408 %current end effector's position/orientation
2409 T = directkinematic(robot, robot.q);
2410
2411 current_conf = compute_configuration(robot, robot.q);
2412
2413 path = lineal_path_planXYZ(P_ini,P_final);
2414
2415 for i=1:size(path,2),
2416     T(1:3,4)=path(:,i);
2417     %several solutions are provided
2418     qinv = inversekinematic(robot, T);
2419     %choose the closest to current position
2420
2421     q=select_closest_joint_coordinates(robot, qinv, robot.q);
2422
2423     robot.q = q;
2424
2425     %Test whether there are joints outside mechanical limits
2426     error = test_joints(robot, robot.q);
2427
2428     drawrobot3d(robot, robot.q);
2429
2430     current_conf = compute_configuration(robot, robot.q);
2431
2432     if error == 1
2433         disp('\nAn error has occurred during the trajectory. Please check angle ranges');
2434         break;
2435     end
2436 end
2437 update_T_Q();
2438 update_sliders();
2439 plot3(path(1,:),path(2,:),path(3,:),'k', 'LineWidth', 3);
2440
2441 draw_target_points();
2442
2443
2444
2445 %draw the targets points on the robots figure
2446 function draw_target_points()
2447 global targets configuration controls
2448 figure(configuration.figure.robot)
2449
2450 s=0.1; %scale
2451
2452 for i=1:controls.num_target_points,
2453
2454     T = targets{i}.T;
2455     p0=T(1:3,4)';
2456     x=p0+s*T(1:3,1)';
2457     y=p0+s*T(1:3,2)';
2458     z=p0+s*T(1:3,3)';
2459
2460     vect_arrow(p0,x,'r')
2461     vect_arrow(p0,y,'g')
2462     vect_arrow(p0,z,'b')
2463     %plot vector names X_i Y_i Z_i
2464     text(x(1)+0.01, x(2)+0.01, x(3)+0.01,targets{i}.name, 'FontWeight', 'bold', 'HorizontalAlignment', 'Center', 'FontSize', 14);
2465 end
2466
2467
2468 function tp = construct_target(target_num)
2469
2470 global targets
2471
2472 T = targets{target_num}.T;
2473 Q = targets{target_num}.Q;
2474 conf = targets{target_num}.conf;
2475
2476 tp = [[T(1,4),T(2,4),T(3,4)],[Q(1), Q(2), Q(3), Q(4)], [conf(1), conf(2), conf(3), conf(4)], [9E9,9E9,9E9,9E9,9E9,9E9]];
2477
2478
2479
2480 %decode a line into the different variables of a target point
2481 function [name, Q, T, conf]=get_targetpoint_from_string(a)
2482
2483 %start decoding the line
2484 [name, remain] = strtok(a,'=');
2485 [token, remain] = strtok(remain,'[');
2486
2487 eval(['target=' remain]);
2488
2489 px=target(1);
2490 py=target(2);
2491 pz=target(3);
2492
2493 Q = target(4:7);
2494 T = quaternion2T(Q, [px py pz]);
2495
2496 conf = target(8:11);
2497
2498
2499
2500
2501 function [instruction_matlab, instruction_rapid, tp1, tp2, joint_coord]=build_instruction_to_eval()
2502
2503 global controls targets robot
2504
2505 s = get(controls.popupmenu_instruction,'String');
2506 i = get(controls.popupmenu_instruction,'Value');
2507 s1=s{i};
2508
2509 tp1=[];
2510 tp1_name=[];
2511 tp2=[];
2512 tp2_name = [];
2513 joint_coord=[];
2514 switch s1
2515     case {'MoveJ','MoveL'}
2516
2517         s = get(controls.popupmenu_target_point,'String');
2518         target_num = get(controls.popupmenu_target_point,'Value');
2519         s2=s{target_num};
2520
2521         s = get(controls.popupmenu_speed,'String');
2522         i = get(controls.popupmenu_speed,'Value');
2523         s3=s{i};
2524
2525         s = get(controls.popupmenu_precision,'String');
2526         i = get(controls.popupmenu_precision,'Value');
2527         s4=s{i};
2528
2529         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2530
2531         tp1=construct_target(target_num);
2532
2533
2534         s = get(controls.popupmenu_target_point,'String');
2535         target_num = get(controls.popupmenu_target_point,'Value');
2536         tp1_name=s{target_num};
2537
2538         instruction_matlab = ['robot=' s1 '(robot, tp1,' sprintf(' ''%s'' ', s3) ',' sprintf(' ''%s'' ', s4) ', robot.tool0, robot.wobj0);'];
2539         fprintf('\n**********************************************\n');
2540         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2541         fprintf('**********************************************\n');
2542
2543        % eval(instruction_matlab);
2544
2545      case 'MoveAbsJ'
2546
2547         s = get(controls.popupmenu_target_point,'String');
2548         target_num = get(controls.popupmenu_target_point,'Value');
2549         s2=s{target_num};
2550
2551         s = get(controls.popupmenu_speed,'String');
2552         i = get(controls.popupmenu_speed,'Value');
2553         s3=s{i};
2554
2555         s = get(controls.popupmenu_precision,'String');
2556         i = get(controls.popupmenu_precision,'Value');
2557         s4=s{i};
2558
2559         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2560
2561
2562         joint_coord=[targets{target_num}.q' 1e9, 1e9, 1e9, 1e9, 1e9, 1e9];
2563
2564
2565         instruction_matlab = ['robot=' s1 '(robot, joint_coord,' sprintf(' ''%s'' ', s3) ',' sprintf(' ''%s'' ', s4) ', robot.tool0, robot.wobj0);'];
2566         fprintf('\n**********************************************\n');
2567         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2568         fprintf('**********************************************\n');
2569
2570        % eval(instruction_matlab);
2571
2572
2573     case 'MoveC'
2574         s = get(controls.popupmenu_target_point,'String');
2575         target_num1 = get(controls.popupmenu_target_point,'Value');
2576         s2=s{target_num1};
2577
2578         s = get(controls.popupmenu_through_point,'String');
2579         target_num2 = get(controls.popupmenu_through_point,'Value');
2580         s3=s{target_num2};
2581
2582         s = get(controls.popupmenu_speed,'String');
2583         i = get(controls.popupmenu_speed,'Value');
2584         vel=s{i};
2585
2586         s = get(controls.popupmenu_precision,'String');
2587         i = get(controls.popupmenu_precision,'Value');
2588         prec=s{i};
2589
2590         instruction_rapid = [s1 ' ' s3 ',' s2 ',' vel ',' prec  ',tool0\Wobj:=wobj0;'];
2591
2592         tp2=construct_target(target_num1);
2593         tp1=construct_target(target_num2);%the through point
2594
2595         instruction_matlab = ['robot=' s1 '(robot, tp1, tp2, ' sprintf(' ''%s'' ', vel) ',' sprintf(' ''%s'' ', prec) ', robot.tool0, robot.wobj0);'];
2596         fprintf('\n**********************************************\n');
2597         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2598         fprintf('**********************************************\n');
2599
2600        % eval(instruction_matlab);
2601
2602     otherwise disp('RAPID instruction not supported');
2603 end
2604
2605
2606
2607 function [instruction_matlab, instruction_rapid]=build_instruction_to_save()
2608
2609 global controls targets robot
2610
2611 s = get(controls.popupmenu_instruction,'String');
2612 i = get(controls.popupmenu_instruction,'Value');
2613 s1=s{i};
2614
2615 tp1=[];
2616 tp1_name=[];
2617 tp2=[];
2618 tp2_name = [];
2619 joint_coord=[];
2620 switch s1
2621     case {'MoveJ','MoveL'}
2622
2623         s = get(controls.popupmenu_target_point,'String');
2624         target_num = get(controls.popupmenu_target_point,'Value');
2625         s2=s{target_num};
2626
2627         s = get(controls.popupmenu_speed,'String');
2628         i = get(controls.popupmenu_speed,'Value');
2629         s3=s{i};
2630
2631         s = get(controls.popupmenu_precision,'String');
2632         i = get(controls.popupmenu_precision,'Value');
2633         s4=s{i};
2634
2635         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2636
2637
2638
2639         s = get(controls.popupmenu_target_point,'String');
2640         target_num = get(controls.popupmenu_target_point,'Value');
2641         tp_name=s{target_num};
2642
2643         instruction_matlab = ['robot=' s1 '(robot,' tp_name ',' ...
2644             sprintf(' ''%s'' ', s3) ',' sprintf(' ''%s'' ', s4) ', robot.tool0, robot.wobj0);'];
2645         fprintf('\n**********************************************\n');
2646         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2647         fprintf('**********************************************\n');
2648
2649        % eval(instruction_matlab);
2650
2651      case 'MoveAbsJ'
2652
2653         s = get(controls.popupmenu_target_point,'String');
2654         target_num = get(controls.popupmenu_target_point,'Value');
2655         s2=s{target_num};
2656
2657         s = get(controls.popupmenu_speed,'String');
2658         i = get(controls.popupmenu_speed,'Value');
2659         s3=s{i};
2660
2661         s = get(controls.popupmenu_precision,'String');
2662         i = get(controls.popupmenu_precision,'Value');
2663         s4=s{i};
2664
2665         instruction_rapid = [s1 ' ' s2 ',' s3 ',' s4 ',tool0\Wobj:=wobj0;'];
2666
2667
2668         %joint_coord=[targets{target_num}.q' 1e9, 1e9, 1e9, 1e9, 1e9, 1e9];
2669
2670         s = get(controls.popupmenu_target_point,'String');
2671         target_num = get(controls.popupmenu_target_point,'Value');
2672         tp_name=s{target_num};
2673
2674         instruction_matlab = ['robot=' s1 '(robot,' tp_name ','...
2675             sprintf(' ''%s'' ', s3) ',' sprintf(' ''%s'' ', s4) ', robot.tool0, robot.wobj0);'];
2676         fprintf('\n**********************************************\n');
2677         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2678         fprintf('**********************************************\n');
2679
2680        % eval(instruction_matlab);
2681
2682
2683     case 'MoveC'
2684         s = get(controls.popupmenu_target_point,'String');
2685         target_num1 = get(controls.popupmenu_target_point,'Value');
2686         s2=s{target_num1};
2687
2688         s = get(controls.popupmenu_through_point,'String');
2689         target_num2 = get(controls.popupmenu_through_point,'Value');
2690         s3=s{target_num2};
2691
2692         s = get(controls.popupmenu_speed,'String');
2693         i = get(controls.popupmenu_speed,'Value');
2694         vel=s{i};
2695
2696         s = get(controls.popupmenu_precision,'String');
2697         i = get(controls.popupmenu_precision,'Value');
2698         prec=s{i};
2699
2700         instruction_rapid = [s1 ' ' s3 ',' s2 ',' vel ',' prec  ',tool0\Wobj:=wobj0;'];
2701
2702
2703
2704         instruction_matlab = ['robot=' s1 '(robot,' s3 ',' s2 ', ' sprintf(' ''%s'' ', vel) ',' sprintf(' ''%s'' ', prec) ', robot.tool0, robot.wobj0);'];
2705         fprintf('\n**********************************************\n');
2706         fprintf('Evaluating instruction:\nRAPID:\n\t%s\nMatlab:\n\t%s\n', instruction_rapid, instruction_matlab);
2707         fprintf('**********************************************\n');
2708
2709        % eval(instruction_matlab);
2710
2711     otherwise disp('RAPID instruction not supported');
2712 end
2713
2714
2715 % --- Executes on selection change in popupmenu_line_reorient.
2716 function popupmenu_line_reorient_Callback(hObject, eventdata, handles)
2717 % hObject    handle to popupmenu_line_reorient (see GCBO)
2718 % eventdata  reserved - to be defined in a future version of MATLAB
2719 % handles    structure with handles and user data (see GUIDATA)
2720
2721 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_line_reorient contents as cell array
2722 %        contents{get(hObject,'Value')} returns selected item from popupmenu_line_reorient
2723
2724
2725 % --- Executes during object creation, after setting all properties.
2726 function popupmenu_line_reorient_CreateFcn(hObject, eventdata, handles)
2727 % hObject    handle to popupmenu_line_reorient (see GCBO)
2728 % eventdata  reserved - to be defined in a future version of MATLAB
2729 % handles    empty - handles not created until after all CreateFcns called
2730
2731 % Hint: popupmenu controls usually have a white background on Windows.
2732 %       See ISPC and COMPUTER.
2733 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2734     set(hObject,'BackgroundColor','white');
2735 end
2736
2737
2738 global controls
2739 controls.popupmenu_line_reorient=hObject;
2740
2741
2742
2743 % SHOWS CURRENT TARGET POINT IN RAPID on the command line
2744 % --- Executes on button press in pushbutton_show_target_point.
2745 function pushbutton_show_target_point_Callback(hObject, eventdata, handles)
2746 % hObject    handle to pushbutton_show_target_point (see GCBO)
2747 % eventdata  reserved - to be defined in a future version of MATLAB
2748 % handles    structure with handles and user data (see GUIDATA)
2749
2750 global controls targets robot
2751
2752 T = directkinematic(robot, robot.q);
2753
2754 %convert to quaternion
2755 Q = T2quaternion(T);
2756 Q=real(Q);
2757 conf = compute_configuration(robot, robot.q);
2758
2759 tp = [[T(1,4),T(2,4),T(3,4)],[Q(1), Q(2), Q(3), Q(4)], [conf(1), conf(2), conf(3), conf(4)], [9E9,9E9,9E9,9E9,9E9,9E9]];
2760 fprintf('\n\ntp:=[[%f,%f,%f],[%f,%f,%f,%f],[%f,%f,%f,%f],[9E9,9E9,9E9,9E9,9E9,9E9]];\n\n',tp(1),tp(2),tp(3),tp(4),tp(5),tp(6),tp(7),tp(8),tp(9),tp(10),tp(11));
2761
2762
2763
2764 % --- Executes on key press with focus on pushbutton_show_target_point and none of its controls.
2765 % SHOWS THE CURRENT TP WHERE THE ROBOT IS SITUATED
2766 function pushbutton_show_target_point_KeyPressFcn(hObject, eventdata, handles)
2767 % hObject    handle to pushbutton_show_target_point (see GCBO)
2768 % eventdata  structure with the following fields (see UICONTROL)
2769 %    Key: name of the key that was pressed, in lower case
2770 %    Character: character interpretation of the key(s) that was pressed
2771 %    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
2772 % handles    structure with handles and user data (see GUIDATA)
2773
2774
2775
2776
2777
2778 % --- Executes on selection change in popupmenu_resolution.
2779 function popupmenu_resolution_Callback(hObject, eventdata, handles)
2780 % hObject    handle to popupmenu_resolution (see GCBO)
2781 % eventdata  reserved - to be defined in a future version of MATLAB
2782 % handles    structure with handles and user data (see GUIDATA)
2783
2784 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_resolution contents as cell array
2785 %        contents{get(hObject,'Value')} returns selected item from popupmenu_resolution
2786
2787
2788 % --- Executes during object creation, after setting all properties.
2789 function popupmenu_resolution_CreateFcn(hObject, eventdata, handles)
2790 % hObject    handle to popupmenu_resolution (see GCBO)
2791 % eventdata  reserved - to be defined in a future version of MATLAB
2792 % handles    empty - handles not created until after all CreateFcns called
2793
2794 global controls
2795 controls.popupmenu_resolution=hObject;
2796
2797
2798 % Hint: popupmenu controls usually have a white background on Windows.
2799 %       See ISPC and COMPUTER.
2800 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2801     set(hObject,'BackgroundColor','white');
2802 end
2803
2804
2805 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2806 % RESETS THE ROBOTS CURRENT JOINTS TO 0
2807 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2808 % --- Executes on button press in pushbutton_reset_all.
2809 function pushbutton_reset_all_Callback(hObject, eventdata, handles)
2810 % hObject    handle to pushbutton_reset_all (see GCBO)
2811 % eventdata  reserved - to be defined in a future version of MATLAB
2812 % handles    structure with handles and user data (see GUIDATA)
2813
2814 global configuration robot controls
2815
2816 update_T_Q();
2817 figure(configuration.figure.robot);
2818
2819
2820 drawrobot3d(robot, robot.q);
2821
2822 final_joints = zeros(1,robot.DOF);
2823 %Use MoveAbsJ to move to zero coordinates
2824 command =['[robot] = MoveAbsJ(robot,final_joints,' sprintf(' ''%s'' ', 'vmax') ',' sprintf(' ''%s'' ', 'fine') ',robot.tool0, robot.wobj0);'];
2825 eval(command);
2826 update_T_Q();
2827 draw_target_points();
2828 update_sliders();
2829
2830
2831 % --- Executes on key press with focus on pushbutton_save_target_point and none of its controls.
2832 function pushbutton_save_target_point_KeyPressFcn(hObject, eventdata, handles)
2833 % hObject    handle to pushbutton_save_target_point (see GCBO)
2834 % eventdata  structure with the following fields (see UICONTROL)
2835 %    Key: name of the key that was pressed, in lower case
2836 %    Character: character interpretation of the key(s) that was pressed
2837 %    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
2838 % handles    structure with handles and user data (see GUIDATA)
2839
2840
2841
2842
2843
2844
2845
2846
2847 function index=find_closest(q,qi)
2848
2849 qq=[];
2850 for i=1:size(q,2),
2851     qq=[qq qi];
2852 end
2853
2854 a=sum((q-qq).^2);
2855
2856 index = min(a);