function M = func_M(I2x,I3x,I2y,I3y,I1z,I2z,I3z,L2,L3,m2,m3,q2,q3)
%FUNC_M
%    M = FUNC_M(I2X,I3X,I2Y,I3Y,I1Z,I2Z,I3Z,L2,L3,M2,M3,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Feb-2026 09:55:35

t2 = q2.*2.0;
t3 = q3.*2.0;
t4 = t2+t3;
t5 = cos(t4);
t6 = L2.^2;
t7 = cos(t2);
t8 = L3.^2;
t9 = cos(q3);
t10 = m3.*t8.*(1.0./4.0);
t11 = L2.*L3.*m3.*t9.*(1.0./2.0);
t12 = I3y+t10+t11;
M = reshape([I2x.*(1.0./2.0)+I3x.*(1.0./2.0)+I1z+I2z.*(1.0./2.0)+I3z.*(1.0./2.0)+t11+I3x.*t5.*(1.0./2.0)+I2x.*t7.*(1.0./2.0)-I3z.*t5.*(1.0./2.0)-I2z.*t7.*(1.0./2.0)+m2.*t6.*(1.0./8.0)+m3.*t6.*(1.0./2.0)+m3.*t8.*(1.0./8.0)+m2.*t6.*t7.*(1.0./8.0)+m3.*t5.*t8.*(1.0./8.0)+m3.*t6.*t7.*(1.0./2.0)+L2.*L3.*m3.*cos(q3+t2).*(1.0./2.0),0.0,0.0,0.0,I2y+I3y+t10+m2.*t6.*(1.0./4.0)+m3.*t6+L2.*L3.*m3.*t9,t12,0.0,t12,I3y+t10],[3,3]);
