Description of compute_configuration
Home > arte3.1.4 > RAPID > functions > compute_configuration.m
compute_configuration
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function conf=compute_configuration(robot, q)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 CONF= COMPUTE_CONFIGURATION(Q)
 Returns the configuration corresponding to the current joint coordinates
 In RAPID the configuration variable is used to distinguish among the
 different solutions for the inverse kinematic problem.
 The variable conf=[cf1 cf4 cf6 cfx] is formed by the position of the
 first, fourth and sixth robot axis. The last component cfx is used for
 special robots requiring an additional component to specify a particular
 pose univoquely. If the angle is positive, the conf value has one of the
 following values:
         1 | 0
        ---|---
         2 | 3
 that can be computed with the formulae: floor(joint_angle x 2/pi)
 if the angle is negative, then
         -3 | -4
         ---|---
         -2 | -1
 computed as: ceil(joint_angle × 2/pi ? 1)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MoveC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
select_closest_configuration %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
select_configuration %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
teach
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONF= COMPUTE_CONFIGURATION(Q)
% Returns the configuration corresponding to the current joint coordinates
% In RAPID the configuration variable is used to distinguish among the
% different solutions for the inverse kinematic problem.
% The variable conf=[cf1 cf4 cf6 cfx] is formed by the position of the
% first, fourth and sixth robot axis. The last component cfx is used for
% special robots requiring an additional component to specify a particular
% pose univoquely. If the angle is positive, the conf value has one of the
% following values:
%         1 | 0
%        ---|---
%         2 | 3
% that can be computed with the formulae: floor(joint_angle x 2/pi)
% if the angle is negative, then
%         -3 | -4
%         ---|---
%         -2 | -1
% computed as: ceil(joint_angle × 2/pi ? 1)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function conf=compute_configuration(robot, q)
%initialize conf data
conf = zeros(1,4);
if q(1)>=0
    cf1 = floor(q(1)*2/pi);
else
    cf1 = ceil(q(1)* 2/pi) - 1;
end
if robot.DOF<4
   return;
end
if q(4)>=0
    cf4 = floor(q(4)*2/pi);
else
    cf4 = ceil(q(4)*2/pi) - 1;
end
if robot.DOF<6
   return;
end
if q(6)>=0
    cf6 = floor(q(6)*2/pi);
else
    cf6 = ceil(q(6)*2/pi) - 1;
end
conf = [cf1 cf4 cf6 0];