Description of MoveL
Home > arte3.1.4 > RAPID > functions > MoveL.m
MoveL
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function robot = MoveL(robot, robtarget, speeddata, zonedata, gripper, Wobj)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   MoveL: Make a linear planning in space
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
get_conf_data Obtain joint configuration values from robtarget data type
obtain_linear_speed compute linear end effector's speed according to speeddata variable
obtain_zone_data given a tag specifying the zone data. Return a radius in meters
select_closest_joint_coordinates %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
test_joint_limits %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
transform_to_homogeneous %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T2quaternion %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
accel %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
directkinematic DIRECTKINEMATIC Direct Kinematic for serial robots.
inversekinematic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
quaternion2T %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
single_joint_spline %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
slerp %%%%%%%%%%%%%%%%
animate ANIMATE(ROBOT, Q)
vect_arrow %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
p_disp
program_robot Para la simulación de un programa
test_initial BEGINMODULE
test_rapid BEGINMODULE
test_simulation se declaran las variables necesarias
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   MoveL: Make a linear planning in space
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function robot = MoveL(robot, robtarget, speeddata, zonedata, gripper, Wobj)
global configuration
fprintf('\nCall to MoveL', robot.name);
%Ttool, transformation from the robot's end to the TCP
Ttool = transform_to_homogeneous(gripper(2:end));
%current position and orientation
T=directkinematic(robot, robot.q);
Ttotal = T*Ttool;
%last target
p0 = Ttotal(1:3,4);
%orientation
Q0 = T2quaternion(Ttotal);
%in this case, plan a linear trajectory from point
%if robot.last_zone_data=='fine'
    %compute target joint coordinates, from the inverse kinematics
    %select desired joint values by using conf data from robtarget
    %select configuration
final_conf = get_conf_data(robtarget);
Ttotal = transform_to_homogeneous(robtarget);
%final position
p1 = Ttotal(1:3,4);
% and orientation
Q1 = T2quaternion(Ttotal);
distance = norm(p1-p0);
%unit vector in the direction of the trajectory normalize
u = (p1-p0)/norm(p1-p0);
speed = obtain_linear_speed(robot, speeddata);
tmax = distance/speed;
%compute current robot speed in modulus. m/s
v_current = 1;
if tmax <= configuration.delta_time
    disp('/RAPID/MOVEL: No movement is performed. Making a null movement of 1 second');
    tmax = 2*configuration.delta_time; %avoid errors
    distance = 1;
    u=[0 0 0]';
end
%local time for the planning
t = [0:configuration.delta_time:tmax]';
%when fine is specified, the radius is zero, otherwise,
%the radius represents a sphere around the target where the
%movement is changed to the next target
radius = obtain_zone_data(zonedata);
if radius == 0 %target point is fine
    %plan an acceleration profile one the line that connects both
    %points. Asume as a one joint planifier
    %[pos, vel, accel] = compute_joint_trajectory(0, distance, t, v_current, 0);
    [pos, vel, accel] = single_joint_spline(0, distance, v_current, 0, t);
else
    %[pos, vel, accel] = compute_joint_trajectory(0, distance, t, v_current, speed);
    [pos, vel, accel] = single_joint_spline(0, distance, v_current, speed, t);
end
%current_conf = compute_configuration(robot, robot.q);
pp=[];
q_line=[];
N=length(pos);
for j=1:N,
    pj = p0 + u*pos(j);
    %interpolate between the initial and final quaternions
    %to find an orientation between both
    [Qm] = slerp(Q0, Q1, (j-1)/N, 0.01);
    %find homogeneous matrix corresponding to pi and Qm
    Ttotal = quaternion2T(Qm, pj);
    pp=[pp T(1:3,4)];
    %find T, of the robot's end points
    T=Ttotal*inv(Ttool);
    %find all the possible solutions to reach T
    qinv = inversekinematic(robot, T);
    %interpolate configuration
    %middle_conf = current_conf*(1-(i-1)/N) + final_conf*((i-1)/N);
    %select at each timestep the closes configuration
    % q=select_closest_configuration(robot, qinv, middle_conf);
    %q=select_closest_configuration(robot, qinv, current_conf);
    q=select_closest_joint_coordinates(robot, qinv, robot.q);
    %store the joint coordinates in a vector for ulterior animation
    q_line = [q_line q];
    %the robot performs the movement until the index found. The coordinates, joint speed and acceleratin
    %are stored and used in the planning of the next point
    robot.q=q;
    robot.qd=zeros(robot.DOF,1);
    robot.qdd=zeros(robot.DOF,1);
    %store all the trajectory for plotting
    %the joint trajectories, speeds and acceleration of susequent movements are
    %store here
   % robot.q_vector=[robot.q_vector q];
   % robot.qd_vector=[robot.qd_vector zeros(robot.DOF,1)];
   % robot.qdd_vector=[robot.qdd_vector zeros(robot.DOF,1)];
    %update current configuration
   % current_conf = compute_configuration(robot, robot.q);
end
%a global time for the planning is computed.
%in this way, the total trajectory of different movements can be plotted
if length(robot.time)==0
    tend = 0;
else
    tend = robot.time(end);
end
t = t + tend;
%store total time
robot.time=[robot.time t'];
%Test whether there are joints outside mechanical limits
test_joint_limits(robot);
%Plot position, velocity and acceleration
%plot_joint_data(robot);
%Now, animate the robot in 3D
animate(robot, q_line);
%Plot an arroy between p0 an p1
vect_arrow(p0,p1,'b')
plot3(pp(1,:),pp(2,:),pp(3,:), 'k', 'LineWidth', 2)