Description of MoveJ
Home > arte3.1.4 > RAPID > functions > MoveJ.m
MoveJ
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function [robot] = MoveJ(robot, robtarget, speeddata, zonedata, gripper, Wobj)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   MoveJ:
   Example: MoveJ(pos_b_rec, 'v1000', 'z100', gripper, wobj0);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
compute_joint_trajectory_indep %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
find_first_in_zone_data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
get_conf_data Obtain joint configuration values from robtarget data type
obtain_joint_speed %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
obtain_zone_data given a tag specifying the zone data. Return a radius in meters
select_configuration %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
synchronize %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
test_joint_limits %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
transform_to_homogeneous %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
directkinematic DIRECTKINEMATIC Direct Kinematic for serial robots.
inversekinematic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
animate ANIMATE(ROBOT, Q)
This function is called by:
p_disp
program_robot Para la simulación de un programa
test_initial BEGINMODULE
test_rapid BEGINMODULE
test_simulation se declaran las variables necesarias
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   MoveJ:
%   Example: MoveJ(pos_b_rec, 'v1000', 'z100', gripper, wobj0);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function [robot] = MoveJ(robot, robtarget, speeddata, zonedata, gripper, Wobj)
global configuration
fprintf('\nCall to MoveJ', robot.name);
%obtain current joint coordinates
q_current= robot.q;
%Ttool, transformation from the robot's end to the TCP
Ttool = transform_to_homogeneous(gripper(2:end));
%compute target joint coordinates, from the inverse kinematics
%select desired joint values by using conf data from robtarget
%select configuration
conf = get_conf_data(robtarget);
Ttotal = transform_to_homogeneous(robtarget);
T = Ttotal*inv(Ttool);
%Obtain end effectors T from desired gripper T
%T=gripper_to_end_effector(gripper, T);
q_final= inversekinematic(robot, T);
%select one of the solutions of the inverse kinematic problem
% solution according to configuration and language
q_final=select_configuration(robot, q_final, conf);
speed = obtain_joint_speed(robot, speeddata);
%when fine is specified, the radius is zero, otherwise,
%the radius represents a sphere around the target where the
%movement is changed to the next target
radius = obtain_zone_data(zonedata);
%find time to perform movement
%[actual_speed, tmax]=synchronize(q_current, q_final, speed);
[actual_speed, tmax]=synchronize(q_current, q_final, speed, robot.accelmax);
if tmax <= configuration.delta_time
    disp('/RAPID/MOVEJ: No movement is performed. Making a null movement of 1 second');
    tmax = 2*configuration.delta_time; %avoid errors
end
%local time for the planning
t = [0:configuration.delta_time:tmax]';
if radius==0
    %compute a smooth trajectory in q and qd
    %in this case, the final speed is zero
    [q, qd, qdd] = compute_joint_trajectory_indep(robot, q_current, q_final, robot.qd, zeros(1,robot.DOF), t);
else
    %in this case, the final speed is selected as the speed selected by the
    %variable speeddata
    [q, qd, qdd] = compute_joint_trajectory_indep(robot, q_current, q_final, robot.qd, actual_speed, t);
end
%finds the first joint coordinates that are inside a radius r of the target
%point
index = find_first_in_zone_data(robot, q, T, radius);
%the robot performs the movement until the index found. The coordinates, joint speed and acceleratin
%are stored and used in the planning of the next point
robot.q=q(:,index);
robot.qd=qd(:,index);
robot.qdd=qdd(:,index);
%store all the trajectory for plotting
%the joint trajectories, speeds and acceleration of susequent movements are
%store here
%robot.q_vector=[robot.q_vector q(:, 1:index)];
%robot.qd_vector=[robot.qd_vector qd(:, 1:index)];
%robot.qdd_vector=[robot.qdd_vector qdd(:, 1:index)];
%a global time for the planning is computed.
%in this way, the total trajectory of different movements can be plotted
if length(robot.time)==0
    tend = 0;
else
    tend = robot.time(end);
end
t = t + tend;
%store total time
robot.time=[robot.time t(1:index)'];
%Test whether there are joints outside mechanical limits
test_joint_limits(robot);
%Plot position, velocity and acceleration
%plot_joint_data(robot);
%Now, animate the robot in 3D
animate(robot, q);
%Plot the trajectory
pp = [];
for i=1:size(q,2),
    T=directkinematic(robot, q(:,i));
    pp=[pp T(1:3,4)];
end
plot3(pp(1,:),pp(2,:),pp(3,:), 'k', 'LineWidth', 2)