Description of adjust_view
Home > arte3.1.4 > tools > adjust_view.m
adjust_view
PURPOSE
ADJUST_VIEW(ROBOT)
SYNOPSIS
function adjust_view(robot)
DESCRIPTION
   ADJUST_VIEW(ROBOT)
   Called to adjust the 3D view of the plotted robot.
   The variable ROBOT stores the current robot's parameters.
    See also DRAWROBOT3D.
   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
   email: arturo.gil@umh.es date:   05/02/2012
CROSS-REFERENCE INFORMATION
This function calls:
drawrobot3d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
follow_line_pa10 Copyright (C) 2012, by Arturo Gil Aparicio
forwarddynamics_demo SCRIPT TEST THE DIRECT DYNAMICS OF THE PUMA 560 ROBOT
forwarddynamics_demo_3dof SCRIPT TEST THE DIRECT DYNAMICS OF THE PUMA 560 ROBOT
inversedynamics_puma560 SCRIPT TO TEST THE DYNAMICS OF THE PUMA 560 ROBOT
kinematics_demo SCRIPT TEST FOR THE KINEMATIC PROBLEM
manufacturing_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
draw_errors_scara_monte_carlo THE DEMO PRESENTS AN ERROR PROPAGATION USING A MONTE-CARLO METHOD
spot_welding_demo SCRIPT TO TEST THE GRAPHIC CAPABILITIES OF THE TOOLBOX: ROBOT IN A MANUFACTURING CELL
SOURCE CODE
%   ADJUST_VIEW(ROBOT)
%   Called to adjust the 3D view of the plotted robot.
%
%   The variable ROBOT stores the current robot's parameters.
%
%    See also DRAWROBOT3D.
%
%   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
%   email: arturo.gil@umh.es date:   05/02/2012
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function adjust_view(robot)
drawrobot3d(robot, robot.q);
fprintf('\n\nADJUST YOUR VIEW AS DESIRED. \nPress any key to continue...\n');
pause
%get adjusted view
[az, el] = view;