Description of compute_jacobian
Home > arte3.1.4 > lib > kinematics > compute_jacobian.m
compute_jacobian
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function J = compute_jacobian(robot, q)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 COMPUTE_JACOBIAN computes the conventional jacobian as a function
 of the joint coordinates. The algorithm is written as is for educational
 purposes and translated from:
   Robot Analysis. The mechanics of Serial and parallel manipulators.
   Lung-Wen Tsai. John Wiley and Sons. ISBN: 0-471-32593-7. Page 186.
 Given the conventional Jacobian computed in this way. The end effectors
 velocity defined as V = [vn wn]' can be computed as V = J*qd, where vn
 and wn are the end effector's linear and angular speed respectively and
 qd is the joint speed.
   See also DIRECTKINEMATIC.
   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
   email: arturo.gil@umh.es date:   26/04/2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
dh DENAVIT Compute an homogeneous transform matrix DH in terms of
directkinematic DIRECTKINEMATIC Direct Kinematic for serial robots.
This function is called by:
compute_end_velocity %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
compute_joint_velocity %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COMPUTE_JACOBIAN computes the conventional jacobian as a function
% of the joint coordinates. The algorithm is written as is for educational
% purposes and translated from:
%
%   Robot Analysis. The mechanics of Serial and parallel manipulators.
%   Lung-Wen Tsai. John Wiley and Sons. ISBN: 0-471-32593-7. Page 186.
%
% Given the conventional Jacobian computed in this way. The end effectors
% velocity defined as V = [vn wn]' can be computed as V = J*qd, where vn
% and wn are the end effector's linear and angular speed respectively and
% qd is the joint speed.
%
%   See also DIRECTKINEMATIC.
%
%   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
%   email: arturo.gil@umh.es date:   26/04/2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function J = compute_jacobian(robot, q)
theta = eval(robot.DH.theta);
d = eval(robot.DH.d);
a = eval(robot.DH.a);
alfa = eval(robot.DH.alpha);
%number of DOF
n = length(theta);
%base rotation
R0 = eye(3);
z = [0 0 1]';
%compute zi vectors
for i=1:n-1,
    DH = dh(robot, q, i);
    R0=R0*DH(1:3,1:3);
    r=DH(1:3,4);
    zi = R0*[0 0 1]';
    z = [z zi];
end
%compute pin vectors that connect the ith reference system with the end
%effector for i=0: n
T = directkinematic(robot, q);
p =[T(1:3,4)];
for i=1:n-1,
    DH = dh(robot, q, i);
    T = inv(DH)*T;
    p = [p T(1:3,4)];
end
%now compute conventional Jacobian
J= [];
for i=1:n,
    %rotational
    if robot.kind(i)=='R'
        Ji =[cross(z(:,i),p(:,i));z(:,i) ];
    else %translational joint
        Ji =[z(:,i); 0];
    end
    J = [J Ji];
end