Description of directkinematic
Home > arte3.1.4 > lib > kinematics > directkinematic.m
directkinematic
PURPOSE
DIRECTKINEMATIC Direct Kinematic for serial robots.
SYNOPSIS
function T = directkinematic(robot, q)
DESCRIPTION
   DIRECTKINEMATIC        Direct Kinematic for serial robots.
     T = DIRECTKINEMATIC(robot, Q) returns the transformation matrix T
   of the end effector according to the vector q of joint coordinates.
    See also DENAVIT.
   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
   email: arturo.gil@umh.es date:   01/04/2012
CROSS-REFERENCE INFORMATION
This function calls:
dh DENAVIT Compute an homogeneous transform matrix DH in terms of
This function is called by:
MoveAbsJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
find_first_in_zone_data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
init_sim_variables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
teach
kinematics_demo SCRIPT TEST FOR THE KINEMATIC PROBLEM
draw_errors_scara PROPAGATE A GAUSSIAN ERROR DISTRIBUTION OF EACH JOINT TO AN ERROR IN
draw_errors_scara_monte_carlo THE DEMO PRESENTS AN ERROR PROPAGATION USING A MONTE-CARLO METHOD
joint_references %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plot_results_line %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
compute_jacobian %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
parameters %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
animate ANIMATE(ROBOT, Q)
SOURCE CODE
%   DIRECTKINEMATIC        Direct Kinematic for serial robots.
%
%     T = DIRECTKINEMATIC(robot, Q) returns the transformation matrix T
%   of the end effector according to the vector q of joint coordinates.
%
%    See also DENAVIT.
%
%   Author: Arturo Gil. Universidad Miguel Hernández de Elche.
%   email: arturo.gil@umh.es date:   01/04/2012
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function T = directkinematic(robot, q)
theta = eval(robot.DH.theta);
d = eval(robot.DH.d);
a = eval(robot.DH.a);
alfa = eval(robot.DH.alpha);
n=length(theta); %number of DOFs
if robot.debug
    fprintf('\nComputing direct kinematics for the %s robot with %d DOFs\n',robot.name, n);
end
%load the position/orientation of the robot's base
T = robot.T0;
for i=1:n,
    T=T*dh(theta(i), d(i), a(i), alfa(i));
end