Description of solve_spherical_wrist2
Home > arte3.1.4 > lib > kinematics > solve_spherical_wrist2.m
solve_spherical_wrist2
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function q = solve_spherical_wrist2(robot, q, T, wrist)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   q = solve_spherical_wrist(robot, q, T, wrist)
   Solves the inverse kinematic problem for a spherical wrist
   robot: robot structure.
   q: vector containing the values of the joints 1, 2 and 3.
   T: orientation of the last reference system.
   wrist: select -1 or 1 for two possible solutions (wrist up, wrist down)
    See also DIRECTKINEMATIC.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
dh DENAVIT Compute an homogeneous transform matrix DH in terms of
This function is called by:
inversekinematic_irb140 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
inversekinematic_irb7600_400_255_m2000 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   q = solve_spherical_wrist(robot, q, T, wrist)
%   Solves the inverse kinematic problem for a spherical wrist
%   robot: robot structure.
%   q: vector containing the values of the joints 1, 2 and 3.
%   T: orientation of the last reference system.
%   wrist: select -1 or 1 for two possible solutions (wrist up, wrist down)
%
%    See also DIRECTKINEMATIC.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function q = solve_spherical_wrist2(robot, q, T, wrist)
% Obtain the position and orientation of the system 3
% using the already computed joints q1, q2 and q3
T01=dh(robot, q, 1);
T12=dh(robot, q, 2);
T23=dh(robot, q, 3);
T03=T01*T12*T23;
x3=T03(1:3,1);
y3=T03(1:3,2);
z3=T03(1:3,3);
% T= [ nx ox ax Px;
%     ny oy ay Py;
%     nz oz az Pz];
a=T(1:3,3);
% find z4 normal to the plane formed by z3 and a
z4=cross(z3, a);    % end effector's vector a: T(1:3,3)
% in case of degenerate solution,
% when z3 and z6 are parallel, choose q(4)=0 as solution
if norm(z4) <= 0.00001
    if wrist == 1 %wrist up
        q(4)=0;
    else
        q(4)=-pi;
    end
else
    cq4=wrist*dot(z4, -y3);
    sq4=wrist*dot(z4, x3);
    q(4)=atan2(sq4, cq4);
end
% solve for q5
T34=dh(robot, q, 4);
T04=T03*T34;
x4=T04(1:3, 1);
y4=T04(1:3, 2);
z5=T(1:3, 3); % The vector a T(1:3,3) is coincident with z5
cq5=dot(z5, y4);
sq5=dot(z5, -x4);
q(5)=atan2(sq5, cq5);
% solve for q6
x6=T(1:3, 1);
T45=dh(robot, q, 5);
T05=T04*T45;
x5=T05(1:3, 1);
y5=T05(1:3, 2);
cq6=dot(x6, -x5);
sq6=dot(x6, -y5);
q(6)=atan2(sq6, cq6);