Description of inversekinematic_irb7600_500_230
Home > arte3.1.4 > robots > ABB > IRB7600_500_230 > inversekinematic_irb7600_500_230.m
inversekinematic_irb7600_500_230
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function [q] = inversekinematic_irb7600_500_230(robot, T)
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   Q = INVERSEKINEMATIC_IRB7600_500_230(robot, T)
   Solves the inverse kinematic problem for the ABB IRB 140 robot
   where:
   robot stores the robot parameters.
   T is an homogeneous transform that specifies the position/orientation
   of the end effector.
   A call to Q=INVERSEKINEMATIC_IRB7600_500_2300 returns 8 possible solutions, thus,
   Q is a 6x8 matrix where each column stores 6 feasible joint values.
   Example code:
   abb=load_robot('abb', 'IRB7600_500_2300');
   q = [0 0 0 0 0 0];
   T = directkinematic(abb, q);
   %Call the inversekinematic for this robot
   qinv = inversekinematic(abb, T);
   check that all of them are feasible solutions!
   and every Ti equals T
   for i=1:8,
        Ti = directkinematic(abb, qinv(:,i))
   end
    See also DIRECTKINEMATIC.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
dh DENAVIT Compute an homogeneous transform matrix DH in terms of
solve_spherical_wrist %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
normalize %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
SUBFUNCTIONS
function q2 = solve_for_theta2(robot, q, Pm)
function q3 = solve_for_theta3(robot, q, Pm)
function qreal = arrange_solutions(q)
SOURCE CODE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Q = INVERSEKINEMATIC_IRB7600_500_230(robot, T)
%   Solves the inverse kinematic problem for the ABB IRB 140 robot
%   where:
%   robot stores the robot parameters.
%   T is an homogeneous transform that specifies the position/orientation
%   of the end effector.
%
%   A call to Q=INVERSEKINEMATIC_IRB7600_500_2300 returns 8 possible solutions, thus,
%   Q is a 6x8 matrix where each column stores 6 feasible joint values.
%
%
%   Example code:
%
%   abb=load_robot('abb', 'IRB7600_500_2300');
%   q = [0 0 0 0 0 0];
%   T = directkinematic(abb, q);
%   %Call the inversekinematic for this robot
%   qinv = inversekinematic(abb, T);
%   check that all of them are feasible solutions!
%   and every Ti equals T
%   for i=1:8,
%        Ti = directkinematic(abb, qinv(:,i))
%   end
%    See also DIRECTKINEMATIC.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) 2012, by Arturo Gil Aparicio
%
% This file is part of ARTE (A Robotics Toolbox for Education).
%
% ARTE is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% ARTE is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Leser General Public License
% along with ARTE.  If not, see <http://www.gnu.org/licenses/>.
function [q] = inversekinematic_irb7600_500_230(robot, T)
%initialize q,
%eight possible solutions are generally feasible
q=zeros(6,8);
%Evaluate the parameters
theta = eval(robot.DH.theta);
d = eval(robot.DH.d);
a = eval(robot.DH.a);
alpha = eval(robot.DH.alpha);
%See geometry at the reference for this robot
L1=d(1);
L2=a(2);
L3=d(4);
A2=a(3);
L6=d(6);
A1 = a(1);
%T= [ nx ox ax Px;
%     ny oy ay Py;
%     nz oz az Pz];
Px=T(1,4);
Py=T(2,4);
Pz=T(3,4);
%Compute the position of the wrist, being W the Z component of the end effector's system
W = T(1:3,3);
% Pm: wrist position
Pm = [Px Py Pz]' - L6*W;
%first joint, two possible solutions admited:
% if q(1) is a solution, then q(1) + pi is also a solution
q1=atan2(Pm(2), Pm(1));
%solve for q2
q2_1=solve_for_theta2(robot, [q1 0 0 0 0 0 0], Pm);
q2_2=solve_for_theta2(robot, [q1+pi 0 0 0 0 0 0], Pm);
%solve for q3
q3_1=solve_for_theta3(robot, [q1 0 0 0 0 0 0], Pm);
q3_2=solve_for_theta3(robot, [q1+pi 0 0 0 0 0 0], Pm);
%Arrange solutions, there are 8 possible solutions so far.
% if q1 is a solution, q1* = q1 + pi is also a solution.
% For each (q1, q1*) there are two possible solutions
% for q2 and q3 (namely, elbow up and elbow up solutions)
% So far, we have 4 possible solutions. Howefer, for each triplet (theta1, theta2, theta3),
% there exist two more possible solutions for the last three joints, generally
% called wrist up and wrist down solutions. For this reason,
%the next matrix doubles each column. For each two columns, two different
%configurations for theta4, theta5 and theta6 will be computed. These
%configurations are generally referred as wrist up and wrist down solution
q = [q1         q1         q1        q1       q1+pi   q1+pi   q1+pi   q1+pi;
     q2_1(1)    q2_1(1)    q2_1(2)   q2_1(2)  q2_2(1) q2_2(1) q2_2(2) q2_2(2);
     q3_1(1)    q3_1(1)    q3_1(2)   q3_1(2)  q3_2(1) q3_2(1) q3_2(2) q3_2(2);
     0          0          0         0         0      0       0       0;
     0          0          0         0         0      0       0       0;
     0          0          0         0         0      0       0       0];
%At this point, we want to asure, that, at least, the function returns
%4 real solutions q(1:4). If any of the solutions q(1:4) is complex, only
%the real part will be returned. If any of the solutions q(5:8) is complex,
%it will not be considered and removed
q = arrange_solutions(q);
%normalize q to [-pi, pi]
q = normalize(q);
% solve for the last three joints
% for any of the possible combinations (theta1, theta2, theta3)
for i=1:2:size(q,2),
    qtemp = solve_spherical_wrist(robot, q(:,i), T, 1,'geometric'); %wrist up
    q(:,i)=qtemp;
    qtemp = solve_spherical_wrist(robot, q(:,i), T, -1, 'geometric'); %wrist up
    q(:,i+1)=qtemp;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% solve for second joint theta2, two different
% solutions are returned, corresponding
% to elbow up and down solution
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function q2 = solve_for_theta2(robot, q, Pm)
%Evaluate the parameters
d = eval(robot.DH.d);
a = eval(robot.DH.a);
%See geometry
L2=a(2);
L3=d(4);
A2=a(3);
%compute L4
L4=sqrt(A2^2+L3^2);
%given q1 is known, compute first DH transformation
T01=dh(robot, q, 1);
%Express Pm in the reference system 1, for convenience
p1 = inv(T01)*[Pm; 1];
r = sqrt(p1(1)^2 + p1(2)^2);
beta = atan2(-p1(2), p1(1));
gamma = (acos((L2^2+r^2-L4^2)/(2*r*L2)));
if ~isreal(gamma)
    disp('WARNING:inversekinematic_irb7600_500_230: the point is not reachable for this configuration, imaginary solutions');
gamma = real(gamma);
end
%return two possible solutions
%elbow up and elbow down
%the order here is important and is coordinated with the function
%solve_for_theta3
q2(1) = pi/2 - beta - gamma; %elbow up
q2(2) = pi/2 - beta + gamma; %elbow down
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% solve for third joint theta3, two different
% solutions are returned, corresponding
% to elbow up and down solution
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function q3 = solve_for_theta3(robot, q, Pm)
%Evaluate the parameters
d = eval(robot.DH.d);
a = eval(robot.DH.a);
%See geometry
L2=a(2);
L3=d(4);
A2=a(3);
%See geometry of the robot
L4=sqrt(A2^2+L3^2);
%the angle phi is fixed
phi= acos((A2^2-L3^2+L4^2)/(2*A2*L4));
%given q1 is known, compute first DH transformation
T01=dh(robot, q, 1);
%Express Pm in the reference system 1, for convenience
p1 = inv(T01)*[Pm; 1];
r = sqrt(p1(1)^2 + p1(2)^2);                                   %sqrt(L3^2 + A2^2);
eta = (acos((L2^2 + L4^2 - r^2)/(2*L2*L4)));                             %pi - asin(L4/r);                   %asin((L4^2)/cos(q(3)));
if ~isreal(eta)
   disp('WARNING:inversekinematic_irb7600_500_230: the point is not reachable for this configuration, imaginary solutions');
eta = real(eta);
end
%return two possible solutions
%elbow up and elbow down solutions
%the order here is important
q3(1) = pi - phi - eta;
q3(2) = pi - phi + eta;
%remove complex solutions for q for the q1+pi solutions
function  qreal = arrange_solutions(q)
qreal=q(:,1:4);
%sum along rows if any angle is complex, for any possible solutions, then v(i) is complex
v = sum(q, 1);
for i=5:8,
    if isreal(v(i))
        qreal=[qreal q(:,i)]; %store the real solutions
    end
end
qreal = real(qreal);