Description of p_disp
Home > arte3.1.4 > RAPID > programs > p_disp.m
p_disp
PURPOSE
SYNOPSIS
function main()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
MoveJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Offs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Reset %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Set %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
SUBFUNCTIONS
function ASIR_DEJAR()
function COGER_PIEZA()
function METER_EN_CAJA()
SOURCE CODE
function main()
global robot
gripper=[1,[[0,0,120]/1000,[1,0,0,0]],[0.1,[0,0,100],[1,0,0,0],0,0,0]];
pos_inicial_1=[[701.14,0,567.0]/1000,[0.5,0,0.866025403784439,0],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
pos_inicial_2=[[500,0,200]/1000,[6.12303176911189E-17,0,1,0],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
%pos de recogida
pos_aprox_rec=[[54.1,-625.4,300.4]/1000,[0.20946,0.62224,0.65494,-0.37418],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
pos_rec=[[54.1,-625.4,300.4]/1000,[0.20946,0.62224,0.65494,-0.37418],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
%posicion dejar
pos_aprox_dej=[[200,-550,300]/1000,[0,0.707106781186547,0.707106781186548,0],[-2,0,-1,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
pos_dej=[[200,-550,300]/1000,[0,0.707106781186547,0.707106781186548,0],[-2,0,-1,0],[9E9,9E9,9E9,9E9,9E9,9E9]];
pieza=0;
%!Reset --> abrir pinza
%!Set --> Cerrar pinza
%inicializar pieza
pieza=0;
robot=MoveJ(robot,pos_inicial_1,'vmax','z100',gripper, robot.wobj0);
robot=MoveJ(robot,pos_inicial_2,'vmax','z100',gripper, robot.wobj0);
for I=1:4,
    ASIR_DEJAR();
    pieza =pieza +1;
end
end
function ASIR_DEJAR()
global robot
    %!Moverse a posición de aproximacion de recogida
    robot=MoveJ(robot,pos_aprox_rec,'v1000','z100',gripper, robot.wobj0);
    COGER_PIEZA;
    %!Moverse a posición base de dejada
    robot=MoveJ(robot,pos_aprox_dej,'v1000','z100',gripper, robot.wobj0);
    METER_EN_CAJA;
end
function COGER_PIEZA()
global robot
    %!Ahora abrir pinza
    Reset do1;
    Waittime 0.1;!esperar apertura
    %!Coger
    robot=MoveL(robot,pos_rec,'v1000','z100',gripper, robot.wobj0);
    %!Ahora cerrar pinza
    Set do1;
    Waittime 0.1; !esperar cierre
    %!Subir por seguridad antes de ir al siguiente punto
    robot=MoveL(robot,pos_aprox_rec,'v1000','z100',gripper, robot.wobj0);
end
function  METER_EN_CAJA()
    global robot
    if pieza==0
        %Bajar para meter primera pieza
        robot=MoveL(robot, Offs(pos_b_dej,0,0,-105),'v1000','fine',gripper, robot.wobj0);
    elseif pieza==1
        robot=MoveL(robot, Offs(pos_b_dej,-55,0,0),'v1000','z100',gripper, robot.wobj0);
        robot=MoveL(robot, Offs(pos_b_dej,-55,0,-105),'v1000','fine',gripper, robot.wobj0);
    elseif pieza==2
        robot=MoveL(robot, Offs(pos_b_dej,0,-55,0),'v1000','fine',gripper, robot.wobj0);
        robot=MoveL(robot, Offs(pos_b_dej,0,-55,-105),'v1000','fine',gripper, robot.wobj0);
    else
        robot=MoveL(robot, Offs(pos_b_dej,-55,-55,0),'v1000','fine',gripper, robot.wobj0);
        robot=MoveL(robot, Offs(pos_b_dej,-55,-55,-105),'v1000','fine',gripper, robot.wobj0);
    end
    %Ahora abrir pinza
    Reset do1;
    Waittime 0.1;
    %Subir por seguridad antes de ir al siguiente punto
    robot=MoveL(robot, Offs(pos_b_dej,0,0,105),'v1000','z10',gripper, robot.wobj0);
end