Description of program_robot
Home > arte3.1.4 > RAPID > programs > program_robot.m
program_robot
PURPOSE
Para la simulación de un programa
SYNOPSIS
This is a script file.
DESCRIPTION
Para la simulación de un programa
CROSS-REFERENCE INFORMATION
This function calls:
MoveJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load_robot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
drawrobot3d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
SOURCE CODE
%Para la simulación de un programa
%robot = load_robot('abb','irb140');
robot.equipment = load_robot('equipment','tables/table_small');
% %robot.equipment = load_robot('equipment','bumper_cutting');
robot.tool= load_robot('equipment','end_tools/parallel_gripper_0');
% robot.piece=load_robot('equipment','cylinders/cylinder_tiny');
% robot.piece.T0= [1 0 0 -0.35;
%              0 1 0 -0.55;
%              0 0 1 0.2;
%              0 0 0 1];
robot.tool.graphical.draw_axes=1
drawrobot3d(robot,[0 0 0 0 0 0])
gripper=[1,[[0,0,120]/1000,[1,0,0,0]],[0.1,[0,0,100],[1,0,0,0],0,0,0]];
tp1=[[0.40000, 0.30000, 0.70000],[1.00000, 0.00000, -0.00000, -0.00000], [0.00000, -1.00000, 1.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp2=[[0,-0.60,0.1],[0.177878,0.301528,-0.099821,-0.931384],[0.000000,-1.000000,-2.000000,0.000000],[9E9,9E9,9E9,9E9,9E9,9E9]];
tp3=[[-0.372948,-0.464961,0.7],[0.033044,-0.436929,0.898885,0.002757],[-2.000000,0.000000,1.000000,0.000000],[9E9,9E9,9E9,9E9,9E9,9E9]];
tp4=[[-0.372948,-0.464961,0.4],[0.033044,-0.436929,0.898885,0.002757],[-2.000000,0.000000,1.000000,0.000000],[9E9,9E9,9E9,9E9,9E9,9E9]];
robot=MoveJ(robot, tp1, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveJ(robot, tp2, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveJ(robot,tp3,'vmax','fine', robot.tool0, robot.wobj0);
robot.tool_activated=1; %Set do1 en RAPID
robot=MoveL(robot,tp4,'vmax','fine', robot.tool0, robot.wobj0);
% robot=MoveL(robot,tp2,'vmax','fine', robot.tool0, robot.wobj0);
% robot=MoveL(robot,tp3,'vmax','fine', robot.tool0, robot.wobj0);
% robot.tool_activated=0; %Reset do1 en RAPID
% robot=MoveJ(robot, tp5, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
% robot=MoveJ(robot, tp1, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
% robot=MoveC(robot, tp2, tp3,  'vmax' , 'fine' , robot.tool0, robot.wobj0);