Description of test_rapid
Home > arte3.1.4 > RAPID > programs > test_rapid.m
test_rapid
PURPOSE
BEGINMODULE
SYNOPSIS
This is a script file.
DESCRIPTION
BEGINMODULE
BEGINTARGETPOINTS
CROSS-REFERENCE INFORMATION
This function calls:
MoveC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
SOURCE CODE
%BEGINMODULE
%BEGINTARGETPOINTS
tp1=[[0.51500, 0.00000, 0.71200],[0.00000, -0.70711, -0.00000, -0.70711], [0.00000, 0.00000, 0.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp2=[[0.66500, 0.10000, 0.71200],[0.00000, -0.70711, -0.00000, -0.70711], [0.00000, -1.00000, 0.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp3=[[0.66500, 0.00000, 0.46200],[0.00000, -0.70711, 0.00000, -0.70711], [0.00000, -2.00000, 1.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp4=[[0.8, 0.00000, 0.2],[0.00000, -0.70711, 0.00000, -0.70711], [0.00000, -2.00000, 1.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp5=[[0.1, -0.40000, 0.4],[0.00000, -0.70711, 0.00000, -0.70711], [0.00000, -2.00000, 1.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
%ENDTARGETPOINTS
robot=MoveJ(robot, tp1, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveL(robot,tp4,'vmax','fine', robot.tool0, robot.wobj0);
robot=MoveL(robot,tp2,'vmax','fine', robot.tool0, robot.wobj0);
robot=MoveL(robot,tp3,'vmax','fine', robot.tool0, robot.wobj0);
robot=MoveJ(robot, tp5, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveJ(robot, tp1, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveC(robot, tp2, tp3,  'vmax' , 'fine' , robot.tool0, robot.wobj0);
%ENDMODULE