Description of test_initial
Home > arte3.1.4 > RAPID > programs > test_initial.m
test_initial
PURPOSE
BEGINMODULE
SYNOPSIS
This is a script file.
DESCRIPTION
BEGINMODULE
BEGINTARGETPOINTS
CROSS-REFERENCE INFORMATION
This function calls:
MoveC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveJ %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MoveL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
SOURCE CODE
%BEGINMODULE
%BEGINTARGETPOINTS
tp1=[[0.40000, 0.30000, 0.70000],[1.00000, 0.00000, -0.00000, -0.00000], [0.00000, -1.00000, 1.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp2=[[0.10000, -0.40000, 0.70000],[0.00000, -0.00000, -0.00000, -1.00000], [-1.00000, -1.00000, 0.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp3=[[0.50000, -0.00000, 0.85000],[1.00000, -0.00000, -0.00000, 0.00000], [0.00000, -1.00000, -3.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
tp4=[[0.50000, -0.00000, 0.25000],[1.00000, -0.00000, -0.00000, 0.00000], [0.00000, -1.00000, -3.00000, 0.00000], [9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]];
%ENDTARGETPOINTS
for i=1:2,
robot=MoveJ(robot,tp1, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveL(robot,tp2, 'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveC(robot,tp3,tp1,  'vmax' , 'fine' , robot.tool0, robot.wobj0);
robot=MoveL(robot,tp4,  'vmax' , 'fine' , robot.tool0, robot.wobj0);
end
%ENDMODULE